### ISSUE TITLE
Typo in docs/design.md

### ISSUE THREAD

**Issue by Freaky** [netheril96/securefs#1]
> If the underlying filesystem supports xattr, so will sucurefs

**Comment by netheril96** [comment]
Fixed in commit af0ef3483b3a76543a404f1945c0c458ea54dd89

**Comment by netheril96** [comment]
A critical security vulnerability has been found in securefs version 0.4.0 to 0.6.0. If you have used these version to encrypt your data, please either migrate to the newest version or some other encryption software.
