### ISSUE TITLE
Documentation for "--askpass" option is misleading/wrong

### ISSUE THREAD

**Issue by mhogomchungu** [netheril96/securefs#100]
The documentation says what is below
```
   --askpass
     When set to true, ask for password even if a key file is used.
     password+keyfile provides even stronger security than one of them
     alone.

```

The ```when set to true``` implies you have to enter either ```--askpass true``` or ```--askpass false``` but both are wrong because this option takes no arguments therefore there is no setting.

I think the ```When set to true, ``` part should be removed.

While here:

1. How does securefs use the keyfile when only the keyfile is given? Does it use it ask it was given or it manipulates it somehow first? Is there a limit to how big a keyfile should be?

2. How does securefs use the combination or a password and a keyfile?

**Comment by netheril96** [comment]
> How does securefs use the keyfile when only the keyfile is given? Does it use it ask it was given or it manipulates it somehow first? Is there a limit to how big a keyfile should be?

It processes it by computing `HMAC` and therefore has no limit.

> How does securefs use the combination or a password and a keyfile

By computing HMAC.
