### ISSUE TITLE
"securefs fix" command error

### ISSUE THREAD

**Issue by Aletron9000** [netheril96/securefs#101]
Hi,

I am using a raspberry pi 4 with raspbian and I recently noticed one of the files in one of my securefs file systems got corrupted and the file no longer has an inode number. The file corruption only exists in the securefs file system because when I check the underlying directory, there are no corrupt files. I tried running "securefs fix" on the underlying directory, but got the message 

"[int securefs::commands_main(int, const char* const*):1427]    securefs::MessageVerificationException: Message for ID 0000000000000000000000000000000000000000000000000000000000000000 at offset 0 does not match the checksum"

I can still mount the directory, put new files in the directory, modify those files, but I can't remove the corrupt file. Any ideas?

Also, just to see what would happen, I tried running the "fix" command on other securefs directories and ran into the same message as above. Maybe I am not using the command correctly? or maybe it's a bug?

**Comment by netheril96** [comment]
It is weird. `0000000000000000000000000000000000000000000000000000000000000000` is the root directory, so if its message verification code is wrong, the whole filesystem should not be able to mount.

Can you reproduce the problem with a fresh repo? If so, post it here along with the password for that repo (use a simple one since we are only testing).

**Comment by Aletron9000** [comment]
I created a new filesystem with the password "tester1234" and created a file named "file.txt" with the word "test" in it and placed it in the root directory of the mounted filesystem. When trying to run the "fix" command on the encrypted directory, i still get the following error.

[Error] [0xb6f7c910] [2020-04-12 14:42:55.410386703 UTC] [int securefs::commands_main(int, const char* const*):1427]    securefs::MessageVerificationException: Message for ID 0000000000000000000000000000000000000000000000000000000000000000 at offset 0 does not match the checksum

**Comment by netheril96** [comment]
Please try the latest commit (1fc109b3c148d903c8fce21ebbd66821071d6d6e)

**Comment by Aletron9000** [comment]
That seemed to have fixed the issue. Thank you!
