### ISSUE TITLE
Dirs in the "secure" area are created with mode "d--x--x--x"

### ISSUE THREAD

**Issue by jmoses** [netheril96/securefs#102]
Which means that I'm unable to back them up.

Would this be expected behavior for some part of the system?

```
> securefs v
securefs 0.11.1-4-g191541b
Crypto++ 8.2
libfuse 29
utf8proc 2.5.0

Hardware features available:
SSE2: true
SSE3: true
SSE4.1: true
SSE4.2: true
AES-NI: true
CLMUL: true
SHA: false
```

**Comment by jmoses** [comment]
Note that this is _very_ few directories, that I'm seeing this on.

**Comment by netheril96** [comment]
What does "secure" area mean?

**Comment by jmoses** [comment]
Oh, sure. Where the encrypted files are mounted from.

**Comment by jmoses** [comment]
![Screenshot from 2020-05-07 21-28-28](https://user-images.githubusercontent.com/6078/81360636-5ef25000-90aa-11ea-8358-6ebdb154af76.png)

Out of about 5k directories in the encrypted source, there's 3 or 4 with the weird permissions.

**Comment by netheril96** [comment]
You can just `chmod` them and be able to back up.

`securefs` does not change the mode when writing files or creating directories. So I am not sure this is an issue of `securefs`. Maybe something else `chmod`ed on them?

**Comment by jmoses** [comment]
Ah, yeah. I mounted up the files, and there are indeed dirs with those permissions. Weird. Thanks!
