### ISSUE TITLE
Precompiled binaries / static linking

### ISSUE THREAD

**Issue by Achim16** [netheril96/securefs#103]
I'm just facing the usual annoying issues when compiling from Source in Linux, at some point Software
does not  compile any longer as some gcc features or  library versions are required which are only  available in the most recent OS version - I'm however not willing to always upgrade the entire system just because of that. Sadly, in contrast to Windows one cannot just install the latest runtimes.

In particular :
re SecureFS - Most recent versions >=0.90 no longer compile in LMDE2 (Debian 8) but stop with errors. My workaround was to compile it in LMDE4 and transfer the binary back to LMDE2.
But - Running the executable doesn't work as well : 
./securefs: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./securefs). 

Would it be possible to provide binaries for all x86_64 (like gocryptfs does) or teach how to compile with static library linking please ?

Thanks

**Comment by netheril96** [comment]
`securefs` already tries to static link as much as possible. But being written in C++, it cannot shave off its reliance on standard C and C++ libraries. `gocryptfs` is written in Go, and Go tries to avoid system dependencies as much as possible. It is an advantage that `securefs` cannot obtain.

In your case, you can cd into a clean directory, and set environment variables below to link statically the standard C++ library

```
export LDFLAGS='-static-libgcc -static-libstdc++'
cmake PATH_TO_SECUREFS
make
```

However, the approach is not guaranteed to work if the glibc version is mismatched.

**Comment by Achim16** [comment]
I followed your advice - it worked, I'm able to use the binary complied in LMDE 4 in LMDE2 now.
Thanks a lot !

**Comment by netheril96** [comment]
I'm surprised that it worked.
