### ISSUE TITLE
[feature request] clean temporary directory

### ISSUE THREAD

**Issue by etmatrix** [netheril96/securefs#105]
I have 2 securefs sometimes mount them on temporary directory and securefs make the destination directory for mount, but after the destory I expect the directory is deleted but it's remain.
Could you delete it when the directory is created by securefs?

**Comment by netheril96** [comment]
You can simply add a `; rmdir YOUR_MOUNT_POINT` to your command.

**Comment by netheril96** [comment]
It is difficult to do this inside `securefs` because the cleanup routine runs before unmount.

**Comment by etmatrix** [comment]
I mount with -b and umount with fusermount -u
