### ISSUE TITLE
Is it only for pure data files ?

### ISSUE THREAD

**Issue by bradiso** [netheril96/securefs#106]
Hi,

I'm trying securefs on Windows 7 x64.

It works fine with data files but I can't get it working with programs.

I tried for example LibreOffice Portable and Python (python-3.7.7-embed-amd64.zip) : they failed to run.

Also, when I open a console in the folder (cmd.exe), .exe .bat extensions behave differently from regular folder : I have to type python.exe, because python without .exe is not found.

Create a simple sample.bat file then try to execute it with sample : it doesn't work, you must type sample.bat

Am I doing something wrong or is it expected behavior ?

Thanks

**Comment by netheril96** [comment]
> I tried for example LibreOffice Portable and Python (python-3.7.7-embed-amd64.zip) : they failed to run.

Could you be more specific? What errors do you encounter? What logs do `securefs` generate? I don't have any problems running python from a `securefs` volume myself.

> Also, when I open a console in the folder (cmd.exe), .exe .bat extensions behave differently from regular folder : I have to type python.exe, because python without .exe is not found.

It may have to do with the fact that `securefs` volume is by default case sensitive, and `cmd.exe` isn't well equipped to handle it. If it bothers you, you can switch to PowerShell, which does not have the same issue.

**Comment by bradiso** [comment]
I think it may come from my system, there must be something wrong because I have too many failures, everything I run from encrypted folder fails, except a self made sample exe doing only a file append.

I will try in a VM with a clean new install of Windows then I'll tell you.

Thanks

**Comment by bradiso** [comment]
Ok, I just installed a clean Windows 10 x64 in a VM, then installed winfsp-1.6.20027, then created "securefs create test" on the desktop
then
"securefs mount test T:"

Pick a portable software from
https://portableapps.com/news

I tried with Mozilla Firefox, Portable Edition 77.0.1, and I installed it in T: (the encrypted folder). Then run it : it fails.

There is something wrong with executables from securefs folder. It is trivial to check.

For Python, I tried again with embedded zip and it fails like on my Windows 7 system. PowerShell does not make it better.
First you need to type python.exe (python without .exe does not work), it starts, then exit by typing exit() : it fails.

May be it works fine on Unix/BSD systems but on Windows it is completly broken. You cannot run programs installed in a securefs folder on Windows. However for data files only it seems to be right.

**Comment by bradiso** [comment]
I investigated a little further.

As you adviced me, --normalization casefold improved things a lot.

Everything is working except I have to add .exe and .bat in console, this is not a big problem.

Sorry for the inconvenience and thanks for your work.

**Comment by netheril96** [comment]
casefold comes with other problems.
