### ISSUE TITLE
[Feature Request] - Mount w/Master Key

### ISSUE THREAD

**Issue by schlomie** [netheril96/securefs#108]
As interest and time allow ...

gocryptfs has a great feature where it spits out the master key at volume creation.  This master key can then be used in an emergency to mount/recover a volume, if the passphrase was ever lost.  Furthermore, it can be used to reconstruct a lost/corrupted config file.

It would be pretty awesome to have something similar in securefs as well, to offer a little more resilience.

Primary request justification:  securefs works on FreeBSD, gocryptfs does not.

**Comment by netheril96** [comment]
The config file includes more information that the encrypted master key. 

> It would be pretty awesome to have something similar in securefs as well, to offer a little more resilience.

You can simply back up the config file. It is no more difficult than backing up the master key.
