### ISSUE TITLE
Showing Version?

### ISSUE THREAD

**Issue by geneticgrabbag** [netheril96/securefs#11]
I didn't see a way of displaying the application's current version like `securefs -v` or `securefs version`.

Couple of questions:

1. Did I just miss this somewhere?
1. Is there anything in the current code that ties the version to the git tag?
1. Would you be open to a pull request for a `version` command?

Thanks in advance!

**Comment by netheril96** [comment]
I haven't given much thought to versioning. I only splash a new version tag now or then when the new commits accumulate enough. What do you think is the best strategy to maintain consistency between the tag and the version compiled into the software?

**Comment by netheril96** [comment]
Added versioning information in 57f0096544b67bb8a15d1d39a669f1f54b9fd01f. Also shows hardware features available.

**Comment by geneticgrabbag** [comment]
man, you are prolific! nicely done.

**Comment by geneticgrabbag** [comment]
Regarding compiling tag information into source code, what about something like this?

https://github.com/smessmer/gitversion

**Comment by netheril96** [comment]
That won't work when user download the source tarball instead of cloning the repo. I'll settle for manual versioning for now. It should not be hard as the project is mostly stable now.

**Comment by netheril96** [comment]
A critical security vulnerability has been found in securefs version 0.4.0 to 0.6.0. If you have used these version to encrypt your data, please either migrate to the newest version or some other encryption software.
