### ISSUE TITLE
Argon2id implementation

### ISSUE THREAD

**Issue by dhammel** [netheril96/securefs#110]
Would you consider implementing argon2id for a choice between the key derivitation method as it seems to be a better choice amongst some users for security?

**Comment by netheril96** [comment]
I've considered it in the past, but the [reference implementation](https://github.com/P-H-C/phc-winner-argon2) is difficult to incorporate in my CMake project.

**Comment by netheril96** [comment]
Implemented in 33979403ddc114362cedeaa9532750c5af55faaf.
