### ISSUE TITLE
Mount storage as mapped network drive?

### ISSUE THREAD

**Issue by joseffrank** [netheril96/securefs#118]
Is it possible to mount the encrypted space as network drive in windows,
like it is provided by rclone? ("--network-mode")
(see https://rclone.org/commands/rclone_mount/#mounting-modes-on-windows)

Somehow Windows seems to optimize file access differently in local vs network mode.
For some lab programs that option in rclone has greatly helped me 
to avoid program freezes, so I'm wondering whether the same might be possible with securefs

**Comment by netheril96** [comment]
I'm not sure WinFsp has such an option.

**Comment by purdieb** [comment]
From what I can tell from the WinFsp design page there is a WinFsp device, WinFsp.net, for network-like filesystems.
https://github.com/billziss-gh/winfsp/wiki/WinFsp-Design#winfsp-device-namespace

I personally have no idea how much work it would take to make that change though.

**Comment by BrsyRockSs** [comment]
The rclone mount command uses the -- network mode option to mount the network disk. It also uses winfsp, but I'm not sure whether it is implemented through winfsp.

**Comment by netheril96** [comment]
I asked about network drive at https://groups.google.com/g/winfsp/c/857T3o4IEA0/m/JlynmQzKAwAJ?utm_medium=email&utm_source=footer

Are you sure this is what you want? @joseffrank
