### ISSUE TITLE
error like this

### ISSUE THREAD

**Issue by gggin** [netheril96/securefs#12]
ubuntu 16.xx
g++
cmake

way: 
cmake .
make
make install
sudo make install

gin@gin-VGN-SR45H-P:~/workspace/securefs$ securefs create ~/ginPlace
Password: 
Retype password: 
POSIXException: No such file or directory # Opening /home/gin/ginPlace/.securefs.json with flags 0301

**Comment by netheril96** [comment]
Directory `~/ginPlace` not already exists?

**Comment by netheril96** [comment]
Should `securefs` creates the directory when nonexistent instead?

**Comment by gggin** [comment]
yes!
and mount command may be same behavior!
Thank you and this feature is easy to use for newbie

**Comment by netheril96** [comment]
Fixed in 49ffb0e11aa72b902de47c9727251adf53a2e173 and cf27f8e51bdc3f1e33fb52b03dd123dfa838c3db.

**Comment by netheril96** [comment]
A critical security vulnerability has been found in securefs version 0.4.0 to 0.6.0. If you have used these version to encrypt your data, please either migrate to the newest version or some other encryption software.
