### ISSUE TITLE
你需要权限来执行此操作

### ISSUE THREAD

**Issue by BrsyRockSs** [netheril96/securefs#122]
OS：win10 1909 18363.592
SECUREFS: 0.11.1
WINFSP: winfsp-1.9.21096
SINKALI: 1.4.8
您好，我尝试使用 SinKali 配合scf来创建一个加密目录，创建和挂载的过程中均没有任何错误提示，但是挂载的磁盘不能新建和写入任何文件
![image](https://user-images.githubusercontent.com/46119880/133363757-1f73cc1f-28a9-40fd-be13-f1311b07457d.png)
我先附上SinKali的日志
![image](https://user-images.githubusercontent.com/46119880/133363827-e9bc59e0-9dcf-4487-a585-7feada4379c9.png)
![image](https://user-images.githubusercontent.com/46119880/133363837-811ad73f-01b3-4e6e-8f98-e293174b4e59.png)

//
我一开始认为可能是SinKali的程序和scf不兼容导致的，所以我尝试了从命令行模式 创建和挂载，但是问题依旧
下面是命令和生成的日志
`securefs create "C:/Users/brsyr/Desktop/test_b" --pass a --format 4`
`securefs mount "C:/Users/brsyr/Desktop/test_b" "R:" --pass a --fsname test_b --trace -v --log J:\log\test_b.txt`
[test_b.txt](https://github.com/netheril96/securefs/files/7166545/test_b.txt)

`securefs create "C:/Users/brsyr/Desktop/test_c" --pass a --format 2`
`securefs mount "C:/Users/brsyr/Desktop/test_c" "R:" --pass a --fsname test_c --trace -v --log J:\log\test_c.txt`
[test_c.txt](https://github.com/netheril96/securefs/files/7166549/test_c.txt)
//
我找到了一篇类似我的问题的issues,其中说您在一次提交中解决winfsp的权限问题,其中有几个命令,但是那好像是winfsp的命令,并不能用在我这里,并且我看到您提交的代码当中也确实添加了相应的代码,希望您能帮我解决这个问题,

期待您的回复
brsy

**Comment by netheril96** [comment]
我好久没有发新版本了。你有没有装VS？可以编译一个新版本试试。

**Comment by BrsyRockSs** [comment]
我尝试在win和linux下使用了很长时间,到目前为止,我没有遇到任何问题,
另外想问下您,有没有不加密文件名的选项
感谢您编写地securefs,真的很厉害,谢谢

**Comment by netheril96** [comment]
为什么想不加密文件名，是怕太长了吗

**Comment by BrsyRockSs** [comment]
之前有个想法对于百度云 天翼云等一些没办法用rclone实时同步下来的云,我想加密后上传上去,之后需要哪个文件,再下载解密,这时候就需要通过文件名来判断了。

**Comment by netheril96** [comment]
呃，如果一个个文件的上传下载，你用7zip或者gpg手动加密解密就好了

**Comment by BrsyRockSs** [comment]
好的。知道了
再次感谢
