### ISSUE TITLE
re: disable or encrypt the swap

### ISSUE THREAD

**Issue by Owyn** [netheril96/securefs#123]
> It is recommended to disable or encrypt the swap and hibernation file. Otherwise plaintext and keys stored in the main memory may be written to disk by the OS at any time.

You can use `VirtualLock` to lock the specified region of the process's virtual address space into physical memory, ensuring that subsequent access to the region will not incur a page fault.

Other security software like keepass is using it to secure passwords from being dupmed into swap file 
http://niki.hammler.net/wiki/GPG:_WinPT_%2B_KeePass_%3D_KeePT 
> Additionally, the plugin forces the page containing the password to reside in RAM by using VirtualLock (i.e., the page is never swapped out to disk). 

https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-virtuallock?redirectedfrom=MSDN

**Comment by Owyn** [comment]
is **everything** really in need of being protected (yea, they'd probably see some of our encrypted files plain in the swap but not all of them)? maybe just protect most important stuff like the main master key (password) at least?

**Comment by netheril96** [comment]
`fsutil behavior set EncryptPagingFile 1` seems a much easier solution
