### ISSUE TITLE
Recovering encrypted volumes -- "invalid password" after upgrade with no password change

### ISSUE THREAD

**Issue by ammongit** [netheril96/securefs#124]
I have several encrypted volumes which have worked fine for some time. They were able to be mounted just yesterday, but today after upgrading my kernel and securefs, now all of my volumes report "invalid password". It's definitely the same password value, as I have not changed it and can retrieve the exact contents from my password manager. None of the utilities like `fix` are available to me as they require the password to be considered valid.

I have downgraded to several different older securefs versions in an attempt to try and open the volumes, but they have all reported the same error.

Do I have any recourse here? Is it possible to manually calculate the encryption key using my password and extract/rebuild the volumes? Are there any system changes which would cause the password hashing process to be done differently?

----

Version information:
```
Linux 5.14.14-arch1-1 #1 SMP PREEMPT Wed, 20 Oct 2021 21:35:18 +0000

securefs 0.12.0 (previously 0.11.1)
Crypto++ 8.5
libfuse 29
utf8proc 2.6.1

Hardware features available:
SSE2: true
SSE3: true
SSE4.1: true
SSE4.2: true
AES-NI: true
CLMUL: true
SHA: true
```

Volume information:
```
Filesystem format version: 2
Is full or lite format: full
Is underlying directory flattened: true
Is multiple mounts allowed: false
Is timestamp stored within the fs: false

Content block size: 4096 bytes
Content IV size: 96 bits
Password derivation algorithm: scrypt
Password derivation iterations: 65536
Per file key generation algorithm: HMAC-SHA256
Content cipher: AES-256-GCM
```

**Comment by teras** [comment]
This is also a "me too" message.
System: Arch Linux with securefs "0.12.0-1"

I tried to downgrade to 0.9.0 but with no luck. Still invalid password.

**Comment by netheril96** [comment]
Can you post your config json with key redacted?

**Comment by netheril96** [comment]
@teras 

Some questions that may help me debug

* Did you upgrade securefs only or the whole system (like with `sudo pacman -Syu`)?
* Do you have any backups?
* Did you sync the repo to cloud? Which cloud?

**Comment by teras** [comment]
- I upgraded the whole system with exactly the same command. Indeed it might have been another library that got upgraded that securefs depends on 
-  I have a borg backup of the repository
- I do have a private remote borg backup.

**Comment by maassen** [comment]
Hello,
I did a system update with pamac-aur. After that I couldn't mount securefs any more.
I had the previous package file left on disk, so I did a 'pacman -U .cache/yay/securefs/securefs-0.9.0-1-x86_64.pkg.tar.xz'
I've backups of my encrypted and decrypted file (via rsync) but no cloud service.
Hopefully that helps for debugging.
Regards,

**Comment by netheril96** [comment]
@teras @maassen Thankfully you both have backups. Can you compare `.securefs.json` file in the current unmountable repo against the backup version to see if any differences are there?

**Comment by ammongit** [comment]
I don't see any difference in the `.securefs.json` now and from backups.

**Comment by netheril96** [comment]
I can't reproduce the issue on Ubuntu. I compiled version 0.9.0, created a repo with format 2 and password `123`, and then compiled 0.12.0 and successfully mounted that repo.

I need time to install Arch linux on a virtual machine to see if I can reproduce it.

Meanwhile, can you compile it with a different compiler (gcc to clang, or clang to gcc)?

**Comment by maassen** [comment]
Hello,
in my case the json files are equal.
Regards,

**Comment by fschuindt** [comment]
I'm facing the same issue now on Manjaro (Arch based). I have upgraded it from AUR and can no longer open my volumes, it will say my password is wrong.

**Comment by netheril96** [comment]
I tried on a latest Manjaro and successfully reproduced the result.

The key point, the latest GCC is wrong (or maybe Crypto++ is not compatible with that version). In fact, when compiling with gcc, all the tests fail, but when compiling with clang, tests succeed.

I am asking the package maintainer to switch to clang for `securefs`, and preferably run tests before installing the program. Meanwhile, you can manually build `securefs` (set environment variable `CC=clang` and `CXX=clang++` first).

**Comment by fschuindt** [comment]
I can confirm that compling the version 0.12.0 with clang worked. Thank you!

My steps:
```
$ git clone --recursive https://github.com/netheril96/securefs.git
$ cd securefs
$ git checkout 0.12.0
$ export CC=clang
$ export CXX=clang++
$ ./linux-build.sh
```

Then moving the compiled binary to `/usr/bin/`.

**Comment by ammongit** [comment]
I can confirm that @fschuindt's build setup was able to work for me.

**Comment by m-r-x-x** [comment]
I am the maintainer of securefs in the AUR.

I've updated the package with using clang as compiler.

**Comment by maassen** [comment]
Congratulations to all involved!
I can confirm the the updated aur package works :-)
Great!
Thank you very much,
Mic
