### ISSUE TITLE
build-linux.sh tests failed (getattr: File name too long)

### ISSUE THREAD

**Issue by eleius** [netheril96/securefs#126]
I cloned (recursively) securefs and run build-linux.sh, the result was:

```
The following tests FAILED:
	  1 - sec_test (Failed)
	  2 - simple_test (Failed)
```

Running ctest --rerun-failed --output-on-failure produces [this output](https://pastebin.com/raw/widmRfr9).

**Comment by netheril96** [comment]
Are you building on ArchLinux?

**Comment by eleius** [comment]
Yes

**Comment by eleius** [comment]
BTW I built this several months ago (on Arch) and used it without issues. Yesterday I re-cloned on a freshly installed Arch and now it won't pass the tests.

**Comment by netheril96** [comment]
You can see the previous discussion [here](https://github.com/netheril96/securefs/issues/124).

To recap, the latest GCC on ArchLinux is bugged, so you need to use `clang` to build it instead. Or just install the package from `pacman`.

I changed the script to include testing specifically to catch this kind of error.
