### ISSUE TITLE
Deletion or problem of .securefs.json

### ISSUE THREAD

**Issue by jojobricolo57** [netheril96/securefs#127]
Hello,

If the .securefs.json file has a problem, if it is erased by mistake or corrupted, what happens?
Is the entire securefs directory permanently unreadable?
Should it be saved for security reasons to avoid any problem?
Or is it possible to recreate it with a command?
Thanks

**Comment by netheril96** [comment]
Yes, all of them are unreadable if .securefs.json is corrupted.

**Comment by netheril96** [comment]
> But is there a possibility or a command to recreate .securefs.json from the password?

Not possible.

To explain it a bit further, most passwords are not random enough to be used as encryption key. So `securefs` and any other reputable encryption program needs to mix passwords with strong random data called salt to create the master encryption key. The salt is recorded in the `.securefs.json` file. Without the salt and with only the password, we cannot recover the master encryption key.

> Or it is totally impossible and therefore it is better to keep a backup copy of .securefs.json?

Yes, you should back it up.
