### ISSUE TITLE
Change password in command line not hidden

### ISSUE THREAD

**Issue by jojobricolo57** [netheril96/securefs#128]
Hello,

When you change the password with the command "securefs.exe chpass" you have to write the passwords blind.
This is good for security, but when the password is long and complicated (for example "&>$^12sda*%d697*/dfsze") it is easy to make a mistake and put a wrong character.
Can we change the password from the command line?
For example:
chpass d:\securefs2\ --oldpass "&>$^12sda*" --newpass "hfjh<^$+-"
This would be much easier and safer to avoid entering a password blindly and then not being able to retrieve it.
I haven't found a command that can do this on the command line.
Thanks

**Comment by jojobricolo57** [comment]
It is risky to paste a password blindly, unfortunately getting it wrong is very easy.
Yes it would be a good thing to add an option to show password when typing, because I used long (20 characters) and complicated passwords with signs like ^ or < and > and if you can't see what you type, you can easily enter another character. And in this case the new password will be wrong and difficult (or impossible) to find the right password.

Thanks to you

**Comment by netheril96** [comment]
After inspection, I found out I had command line option for password in other modes. So I've implemented your original proposal.
