### ISSUE TITLE
[BUG] Can't build it on ubuntu 21.10

### ISSUE THREAD

**Issue by vitonsky** [netheril96/securefs#129]
I can't build securefs.

Commit: dafa560fd8dc9850d0eda7db1aaa17b8ffb65b58
My OS: ubuntu 21.10

![image](https://user-images.githubusercontent.com/86191922/164986563-7f6e39ee-9cd2-42b4-970f-616f2ae07876.png)
![image](https://user-images.githubusercontent.com/86191922/164986579-3e40b42f-a169-498f-b84a-e1559e6b2bb6.png)

Why and how fix it? Is the master branch always contain consistent code?

**Comment by netheril96** [comment]
This seems to be an incompatibility of test framework of the compiler on your os. Let me investigate tomorrow.

**Comment by netheril96** [comment]
If you want to try, you can replace the catch.hpp from the latest release.

**Comment by vitonsky** [comment]
> If you want to try, you can replace the catch.hpp from the latest release.

I did it, but it's have same content. Even `git status` is not shown changes.

I'll wait updates from you. Thanks.

**Comment by netheril96** [comment]
The root cause is that Ubuntu 21 changes the macro `SIGSTKSZ` from a compile time constant to a function call to `sysconf`. This breaks the assumption of the dependency Catch.

**Comment by vitonsky** [comment]
> The root cause is that Ubuntu 21 changes the macro `SIGSTKSZ` from a compile time constant to a function call to `sysconf`. This breaks the assumption of the dependency Catch.

Ok. So, how i can build it for my OS?

**Comment by netheril96** [comment]
> > The root cause is that Ubuntu 21 changes the macro `SIGSTKSZ` from a compile time constant to a function call to `sysconf`. This breaks the assumption of the dependency Catch.
> 
> Ok. So, how i can build it for my OS?

I've fixed in the latest commit. You can just pull it and rebuild.

**Comment by vitonsky** [comment]
Cool! Compiled successful, thank you
