### ISSUE TITLE
feat: Implement splitting files to chunks

### ISSUE THREAD

**Issue by vitonsky** [netheril96/securefs#131]
At this time, all files is encrypted one-to-one - for each file we create one encrypted file.

This is not so secure, because enemies can analyze content of our encrypted container. They can know about number of files and about its size.

Your implementation is already hide our directory structure, this is very good. Let's improve security.

I suggest to split each original file to few chunks with pseudo random size (maybe in some range) and keep info about next chunk in head of each chunk. This give us more performance compare to CryFS where we use blocks to keep data and shall to read very many small files. But this implementation is still give us high security level, especially when we keep more than 1-2 file in container

**Comment by vitonsky** [comment]
We will split each file to any number of chunks. We'll just start read file and do chose random size for chunk, copy this segment to encrypted file, then do it with next segment and next and next, till whole file will moved.

For same file we may get 1-5 segments or 2000 depends on random. We also may set range, to chunk size, for example 1Mb-3Gb for big files, 1kb for small files and other rules like this. Main idea - keep file to unpredictable number of chunks.

To implement this, we also must decide how we'll implement logic of editing file. At this time i don't have ideas about optimal implementation of this. We may modify existing chunks to keep performance.

Also, we must think how to prevent analysis by timestamps. If enemy will see 10 files modified at one time, so they can know which file we are modified. So maybe we should change timestamps to random values

**Comment by netheril96** [comment]
> Your implementation is already hide our directory structure, this is very good. Let's improve security.

I didn't work on that approach any further and kept only status quo, because I found it difficult to work with cloud sync such as Dropbox or Google Drive.

**Comment by vitonsky** [comment]
What about future of this project? Is you will develop and make new features like this?

**Comment by netheril96** [comment]
I do develop new features, but only on lite format.

**Comment by netheril96** [comment]
If you want to have an encrypted filesystem that fully hides filesystem metadata, you can use VeraCrypt or FileVault or BitLocker. They all support creating a volume out of a single file. That approach doesn't work well with Cloud Sync, but so are all such approaches that stores filesystem metadata in files.
