### ISSUE TITLE
Documentation for --max-padding

### ISSUE THREAD

**Issue by dhammel** [netheril96/securefs#133]
Hello,

in version 0.13.0 compiled on linux, trying to use this option doesn't appear obfuscate it's file size. I may have done it wrong, as I sort of guessed since I don't see any documentation added explaning it. Does this work in file size increment like Bytes, KB, MB..? So if using a a # like 128, would this add up to 128KB of random data to the underlying encrypted file? When using that (--max-padding 128) during creation on file system format 2, adding a 400MB to the mounted directory, it's encrypted version still same size. The info of an ecrypted file system shown by securefs doesn't even show that max padding option was enabled, which I would have expected.

Cryptomator for example will add anywhere up to 10% (unless they changed it recently), so if encrypting a 100MB file it will add anywhere up to 10MB of random data to hide it's true size.

Can you add this option/explanation to the documentation? I am not sure if my use out of it is wrong, as to why it doens't seem like its doing anything or if its a bug since I know the option is new

Thank you

**Comment by netheril96** [comment]
The padding size is in bytes. Maybe you can try a larger padding size to see if it visibly changes the underlying file size.

**Comment by dhammel** [comment]
@netheril96 

Yes, it does have a different file size now when I used 10000000 as a test. Could you maybe add the mention of it being in bytes in the --help of securefs create? 

If I may ask, is there a reccomended value to balance security with performance? Adding up to 10mb as in what I did for this test, seem too muh when adding lots of files, it may waste too much disk space overtime.

**Comment by netheril96** [comment]
> Yes, it does have a different file size now when I used 10000000 as a test. Could you maybe add the mention of it being in bytes in the --help of securefs create?

I will in the next release.

> If I may ask, is there a reccomended value to balance security with performance? Adding up to 10mb as in what I did for this test, seem too muh when adding lots of files, it may waste too much disk space overtime.

It is up to each user to decide. I personally do not use any padding and only implement this because too many people ask for it.

**Comment by netheril96** [comment]
In addition, the performance cost of padding comes not only from the increased file size, but also

* Every `getattr` call now needs to open the file and read the header.
* Listing the directory may need to open all files in that directory.
* Read/write are no longer aligned to block boundaries.

These performance costs are a result of how FUSE kernel is designed, and will be present even if max-padding=1.

**Comment by dhammel** [comment]
Ok, well 1000000 (aka 1MB) seems good and doesn't affect performance as much. 

Ubuntu had recently gotten rid of fuse from its repo, so with 22.04, its been replaced with kio-fuse (fuse3?), So I didn't know if there might have needed to be support for it in securefs or not. Not sure whats different with kio-fuse, didn't do much research on it yet but so far still works.
