### ISSUE TITLE
securefs command not foound after running ./linux-build.sh

### ISSUE THREAD

**Issue by Saik0-Minx** [netheril96/securefs#136]
any help would be greatly appreciated. I am not sure if i am missing a step or something when following the build instructions for linux.  
I run sudo ./linux-build.sh to complete the install and it completes with all for test are passed but when i actually try to use securefs --help it just tells me the command is not found. im not sure if there is something else is should be doing first or not and id really like to try this out so any advice??

**Comment by bsnipes** [comment]
After your ./linux-build.sh completes, you will see at the bottom something like the below:

++ realpath ./securefs
+ SECUREFS_BINARY_PATH=/dev/shm/securefs-build-OCeOO/securefs
+ echo 'Please copy /dev/shm/securefs-build-OCeOO/securefs to anywhere in your $PATH to use it'
Please copy /dev/shm/securefs-build-OCeOO/securefs to anywhere in your $PATH to use it

You will need to follow the instructions on the last line and copy the securefs file somewhere else in your PATH (like /usr/local/bin) and then you should be able to consistently run it.

**Comment by Saik0-Minx** [comment]
thank you that worked
