### ISSUE TITLE
Crash: pure virtual method called

### ISSUE THREAD

**Issue by tari3x** [netheril96/securefs#137]
A crash occurred. I'm not sure where to look for the core file, but can have a more thorough search if you think that would help.

```
$ securefs mount ~/synology/crypt/secure/ ~/crypt/synology-secure-open/ 
Enter password:
[Info] [0x7fbb68ce2700] [2022-08-27 20:41:30.691246624 UTC] [void* securefs::lite::init(fuse_conn_info*):117]    init
pure virtual method called
terminate called without an active exception
```

**Comment by tari3x** [comment]
Perhaps worth mentioning that I'm using securefs over sshfs (something that encfs was doing really well).

**Comment by netheril96** [comment]
What is your platform?

I suspect this is a bug in the compiler interprocedural optimization. Can you build from the branch `noipo` (https://github.com/netheril96/securefs/tree/noipo) and try again?

**Comment by netheril96** [comment]
Alternatively, you can download the prebuilt binary [here](https://github.com/netheril96/securefs/actions/runs/2941534286)

**Comment by tari3x** [comment]
Switched, will see how it goes.

**Comment by netheril96** [comment]
I can't reproduce this on Kubuntu 22.04, with `securefs` overlaying over `sshfs`. Can you give more details on how this error is triggered? Did it happen right after you mounted it, or did you interact with the mounted folder in any way before the crash?

**Comment by netheril96** [comment]
Also, your operating system and compiler.

Hmm, maybe I should add a bug reporting function.

**Comment by tari3x** [comment]
I don't remember seeing this crash since I switched to the noipo branch, but happy to switch back if you think that would be useful.

My vague impression is that this is triggered when I lose the connection for sshfs and then recover it again.

**Comment by tari3x** [comment]
I spoke too soon - it happened again. I "think" I'm using the noipo branch (Merge: 10d6f17 b02a7c3).

I'm on OpenSuSe 15.2 with gcc (SUSE Linux) 7.5.0. Let me know if there's any more info I can collect!

**Comment by tari3x** [comment]
Doesn't seem to be due to the underlying sshfs problem. Rather the last time it was triggered, I was trying to copy some files from (securefs over sshfs) into (encfs on local disk).

**Comment by netheril96** [comment]
Let me add better logging and tracing.

**Comment by netheril96** [comment]
OK, I cannot find the cause so I cannot fix it now. But I added a new branch `stacktrace` that will print the stack trace if `pure virtual method called` happens again. Can you try it? You need to run `sudo zypper install libboost_stacktrace1_75_0-devel` first.

Or take this precompiled binary (you still need to install boost).
[securefs.zip](https://github.com/netheril96/securefs/files/9843730/securefs.zip)

**Comment by tari3x** [comment]
I installed libboost_stacktrace1_66_0-devel (that's what my system comes with), but I'm getting
```
CMake Error at CMakeLists.txt:116 (add_executable):
  Target "securefs" links to target "Boost::stacktrace_basic" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```

Should I try harder to get version 75?

**Comment by netheril96** [comment]
Try pulling and rebuilding.

**Comment by tari3x** [comment]
Works, thanks! Deployed that, will let you know if it blows up again.

**Comment by popflag** [comment]
@netheril96 This problem also exists on MacOS
Searching text with ripgrep is 100% reproducible

```
Enter password:
[Info] [0x1163a5e00] [2022-10-28 05:59:00.260311000 UTC] [virtual int securefs::MountCommand::execute():1327]    Mounting as a Unicode normalized filesystem
[Info] [0x70000b96f000] [2022-10-28 05:59:00.284613000 UTC] [void *securefs::lite::init(struct fuse_conn_info *):117]    init
libc++abi: Pure virtual function called!
[1]    15558 abort      securefs mount ~/encrypt/blahblah
```

**Comment by tari3x** [comment]
```
securefs::lite::FileSystem::translate_path(securefs::StringRef, bool):154]    Pure virtual method called.
Stack trace:

Translate path /incoming into P9G4SAU3RM6ACHXMM4RGS5RW4CNZIQTKG6VPQQS
[Trace] [0x7f7b17fff700] [2022-11-02 00:44:11.356394602 UTC] [int securefs::lite::opendir(const char*, fuse_file_info*):191]    Function ends with arguments ("/incoming", {fh=0x0x7f7b0401c820, flags=0304000}) and return code 0
 0# __cxa_pure_virtual in securefs
 1# CryptoPP::BlockTransformation::AdvancedProcessBlocks(unsigned char const*, unsigned char const*, unsigned char*, unsigned long, unsigned int) const in securefs
 2# CryptoPP::CTR_ModePolicy::OperateKeystream(CryptoPP::KeystreamOperation, unsigned char*, unsigned char const*, unsigned long) in securefs
 3# CryptoPP::AdditiveCipherTemplate<CryptoPP::AbstractPolicyHolder<CryptoPP::AdditiveCipherAbstractPolicy, CryptoPP::CTR_ModePolicy> >::ProcessData(unsigned char*, unsigned char const*, unsigned long) in securefs
 4# securefs::AES_SIV::decrypt_and_verify(void const*, unsigned long, void const*, unsigned long, void*, void const*) in securefs
 5# securefs::lite::readdir(char const*, void*, int (*)(void*, char const*, stat const*, long), long, fuse_file_info*) in securefs
 6# fuse_fs_readdir in /lib64/libfuse.so.2
 7# 0x00007F7B254BB438 in /lib64/libfuse.so.2
 8# 0x00007F7B254C1F62 in /lib64/libfuse.so.2
 9# 0x00007F7B254C30F1 in /lib64/libfuse.so.2
10# 0x00007F7B254BFD93 in /lib64/libfuse.so.2
11# 0x00007F7B25091539 in /lib64/libpthread.so.0
12# clone in /lib64/libc.so.6
```

**Comment by netheril96** [comment]
Thanks. I'll need time to investigate the cause.

**Comment by netheril96** [comment]
What's your output of `securefs v`?

**Comment by tari3x** [comment]
```
 securefs v
securefs 0.13.0-13-g79ac50f
Crypto++ 8.6
libfuse 29
utf8proc 2.7.0

Hardware features available:
SSE2: true
SSE3: true
SSE4.1: true
SSE4.2: true
AES-NI: true
CLMUL: true
SHA: false
```

**Comment by netheril96** [comment]
One hypothesis goes out of the window 😔

**Comment by netheril96** [comment]
I pushed a possible fix. Can you `git pull` and rebuild on the `stacktrace` branch?

**Comment by tari3x** [comment]
Thanks, updated! Will let you know how it goes!

**Comment by netheril96** [comment]
I'll assume that the latest fix is good enough. Feel free to re-open if it resurfaces.

**Comment by tari3x** [comment]
Sounds good, haven't seen issues so far!
