### ISSUE TITLE
copy-paste (ctrl-c, ctrl-v) in dolphin doesn't work

### ISSUE THREAD

**Issue by tari3x** [netheril96/securefs#138]
Weirdest issue - when I copy-paste in dolphin using C-c C-v, nothing happens. At the same time, dragging the file, or using a cp command works just fine. 

This only happens with securefs - copy-pasting in other mounts (say, encfs) works as expected.

Any clue what that could be? I'm amazed that the filesystem has any influence on that - seems like a horrible design. But there we are. Let me know what experiments I should run!

**Comment by netheril96** [comment]
I'm able to reproduce it sometimes. But it is difficult to find out why.

**Comment by tari3x** [comment]
In my case I'm able to reproduce it reliably - the paste option is there when you right click, but is greyed out. Should hopefully be possible to figure out the conditions under which dolphin greys it out. Gotta be something related to file/folder permissions?

**Comment by netheril96** [comment]
When I mount with `--trace`, it becomes possible to paste again.

Is it the same for you?

**Comment by tari3x** [comment]
Yep. A proper heisenbug, how cute!

**Comment by tari3x** [comment]
Ah, no, I spoke too soon. Still broken. I'll try to capture a trace...

**Comment by tari3x** [comment]
Looks fixed to me! Thanks a lot!
