### ISSUE TITLE
Is there any max file size limitation like 64GB due to GCM mode?

### ISSUE THREAD

**Issue by shujaat-github** [netheril96/securefs#139]
I am worrying if there is any file size limitation due to the GCM mode. Can someone please clear up my confusion?

**Comment by netheril96** [comment]
Yes. [Here](https://github.com/netheril96/securefs/blob/b02a7c3034ac6c75ed9ffb1fbfaa49997b995892/sources/lite_stream.cpp#L117) is a check. For the default block size of 4096, the file size limit is (2^31 - 1) * 4096 bytes or slightly less than 8 TiB.

**Comment by netheril96** [comment]
If you want larger files, you can raise the block size when creating the repo.

**Comment by netheril96** [comment]
Note: the 64GB limit for AES-GCM is per (key, nounce) pair. In `securefs`, each block has an independent nounce. The limit comes from elsewhere.

**Comment by shujaat-github** [comment]
@netheril96 I wonder why  **MAX_BLOCKS** has been set to **(1ULL << 31) - 1**?
Here let **N = 31** then isn't it possible for **N to be greater than 31** to allow to encrypt much larger file?
