### ISSUE TITLE
Why MAX_BLOCKS has been set to (1ULL << 31) - 1?

### ISSUE THREAD

**Issue by shujaat-github** [netheril96/securefs#140]
@netheril96 I wonder why  **MAX_BLOCKS** has been set to **(1ULL << 31) - 1**?
Here let **N = 31** then isn't it possible for **N to be greater than 31** to allow to encrypt much larger file?

**Comment by netheril96** [comment]
https://security.stackexchange.com/a/202071

The max is 2**32, but I want to be conservative, given a file may be overwritten.

**Comment by netheril96** [comment]
If you want larger file support, just use larger blocks.

**Comment by shujaat-github** [comment]
@netheril96 I wonder that how gocryptfs using GCM claim that there is no file limit https://github.com/rfjakob/gocryptfs/issues/691#issuecomment-1248354753

Please pardon my ignorance as I am new to this field.

**Comment by netheril96** [comment]
They simply don’t know the limits of AES GCM.

**Comment by netheril96** [comment]
> Any help or link to reference material will be greatly appreciated.

I already gave out a link. That is only an stackexchange answer, but the answer contains links to more authoritative references, like [this one](https://tsapps.nist.gov/publication/get_pdf.cfm?pub_id=51288#page=29)

> The total number of invocations of the authenticated encryption function shall not exceed
232, including all IV lengths and all instances of the authenticated encryption function with
the given key.

**Comment by shujaat-github** [comment]
@netheril96 Appreciate your help! Thank you for clearing up my confusion.
