### ISSUE TITLE
Windows install question!

### ISSUE THREAD

**Issue by rongliangtang** [netheril96/securefs#141]
Hi, I meet some questions when I install scurefs in my win10. I have installed winfsp aned vs2017. But when I click the securefs.exe, it flashs back. I don't how to solve the problem. Could you give me some suggestion?
![Uploading 图片.png…]()

**Comment by netheril96** [comment]
You need to run it in a cmd or powershell. I haven’t build a GUI for it.

**Comment by rongliangtang** [comment]
> You need to run it in a cmd or powershell. I haven’t build a GUI for it.

Thankyou I solve the problem! You are a nice man.
