### ISSUE TITLE
Source code learning problem

### ISSUE THREAD

**Issue by rongliangtang** [netheril96/securefs#142]
Hi，I am a freshman in c++. I want to learn this program，but I don’t know how to run it. For example, what IDE is used and in what order. Could you tell me how to run this source code
. It will help me to learn this program!

**Comment by rongliangtang** [comment]
What’s more, I meet cmake problem in visual studio 2022. The error is about ninja, and I don’t know how to solve the error. Could you give me some suggestions? Thank you!

**Comment by netheril96** [comment]
I usually use VSCode.
