### ISSUE TITLE
关于fuse读写实现中锁的问题

### ISSUE THREAD

**Issue by rongliangtang** [netheril96/securefs#145]
您好，我最近在学习您这个项目。我看重写fuse中write和read的时候，对代码区域加了互斥锁后，还对文件加了flock文件锁。为什么对代码加了互斥锁后，还要加flock文件锁，这里我有点不太理解。希望您能指点一下，谢谢！！

**Comment by netheril96** [comment]
因为用户可以多次打开同一个文件（获得不同的file descriptor），或者用不同的路径打开同一个文件（有hardlink的时候），这时我需要确保所有操作是互斥的

**Comment by rongliangtang** [comment]
谢谢您的回答，我还是有点不理解为什么要对代码区域加互斥锁，是哪里会导致竞争呢？以重写的write为例，我看mutex定义在类里面，如果多个线程同时对一文件进行读写，对代码区域加的互斥锁应该是不起作用的吧，因为每个线程对应的对象不一样。那对代码区域加互斥锁的作用是什么呢，这里我有点不太理解，希望您能指点一下！！谢谢！

> 因为用户可以多次打开同一个文件（获得不同的file descriptor），或者用不同的路径打开同一个文件（有hardlink的时候），这时我需要确保所有操作是互斥的

**Comment by netheril96** [comment]
有两种潜在的冲突

* 同一个程序的不同线程同时读写同一个file descriptor/handle，反应到securefs里就是同一个`File`被同时读写。为了保证它内部的数据结构的安全，需要mutex
* 不同进程的程序用不同的file descriptor去读写同一个文件（可能是打开多次，也可能是硬链接），反应到securefs里就是不同`File`被同时读写，但是写入的数据在操作系统里是同一个区域。为了保证这种情况的安全，需要file lock

**Comment by rongliangtang** [comment]
您说的操作同一个进程中的同一个fd，反应到securefs中是同一个File我能理解，但是似乎在同一个进程中不会出现不同线程操作同一个fd的情况，我在securefs中调试过并且自己写了简单的代码去测试，都没有出现同一个进程中不同线程操作同一个fd的情况。请问您说的同一个进程中不同线程操作同一个fd的情况在什么时候会发生呢？希望您能指点一下！！谢谢！！

**Comment by netheril96** [comment]
写一个测试程序，开一个fd，用多个线程去并行读写

也许libfuse有内部的锁防止这种情况发生，但我不想依赖那个

**Comment by rongliangtang** [comment]
好的，谢谢您，大概理解了。
