### ISSUE TITLE
关于full format中多个securefs进程操作同一数据目录问题

### ISSUE THREAD

**Issue by rongliangtang** [netheril96/securefs#146]
您好，我近期在学习您的项目。
我发现lite format中多个securefs进程操作同一数据目录，不会出现数据冲突，数据都是一致的。而在full format中多个securefs进程操作同一数据目录，会出现数据冲突问题，不同进程中的数据不是一致的。这里我有点不理解，为什么lite中数据是一致同步的，而full format中数据不一致，希望您能指点一下！

**Comment by netheril96** [comment]
> full format中多个securefs进程操作同一数据目录

并不能，有一个lock文件防止这一点
