### ISSUE TITLE
securefs mount on mounted rclone's remote broken after v.0.12

### ISSUE THREAD

**Issue by chromotion** [netheril96/securefs#147]
My setup:
Win10 21H2 10.0.19044.1586
rclone v.1.60.1
WinFsp v.1.12.22301

After upgrade to v.0.13 mounting of any rclone's remote is broken, securefs's output:

![capture_2022-11-24_112455](https://user-images.githubusercontent.com/14054246/203830746-267021a5-8111-459c-80b5-e6ac973b465b.png)

Error message on English: The volume does not contain a recognized file system. Please make sure that all required file system drivers are loaded and that the volume is not corrupted.

I tried old versions of rclone… **FAIL**
I tried different remotes of rclone… **FAIL**
I tried other versions of Windows on VM… **FAIL**
I tried creating FS with option "--pbkdf pkcs5-pbkdf2-hmac-sha256" and then mounting it on rclone remote… **FAIL**
I tried mounting SMB-storage (not rclone)… **PASS**
I tried copying files from mounted with v.0.12 to local drive and then mounting it with v.0.13… **PASS**

v.0.12 works nice at all.

**Comment by netheril96** [comment]
Uh, before I fix the problem, you should regenerate your repo and move all your files to the new one. You have posted your master key in the cleartext. Note that changing the password won't change the master key. Only a new repo will do.

**Comment by chromotion** [comment]
Please, don't worry about this key, because it was a test repo.

**Comment by netheril96** [comment]
Can you try this release: https://github.com/netheril96/securefs/suites/9532166131/artifacts/453036279?

**Comment by chromotion** [comment]
Seems like a works propertly. Very good. 👍
