### ISSUE TITLE
Feature request: Add ability to run in the background.

### ISSUE THREAD

**Issue by mhogomchungu** [netheril96/securefs#15]
The common pattern with these FUSE based projects that encrypt folders is to run in the background by default with an option to run in foreground to override the default.

What was the reason for deciding to run the project in the foreground and with no option to run in the background?

**Comment by netheril96** [comment]
Option `-b` is for mounting in the background. Run `securefs m --help` for a list of all options. 

Foreground is set to be the default so that any error message, which may contain sensitive information like file names, are kept in memory instead of written to disk.

**Comment by mhogomchungu** [comment]
Ok,i didnt notice the option. Thanks.

I have a project called cryfs-gui[1] and i just added the ability to create and unlock securefs volumes. 

[1] http://mhogomchungu.github.io/cryfs-gui/

![screenshot_20160801_165836](https://cloud.githubusercontent.com/assets/3496115/17296356/849f9304-5809-11e6-8f72-66a28f8756a6.png)

**Comment by mhogomchungu** [comment]
Just though i should write to inform that i have changed the name of my project from "cryfs-gui" to "SiriKali" and the front page for the new name is: https://mhogomchungu.github.io/sirikali/

I though i should change the name and use a neutral one since the tool nolonger works with only cryfs.
