### ISSUE TITLE
Issue while compiling on raspberry pi 4b or cross-compile

### ISSUE THREAD

**Issue by csschroedi** [netheril96/securefs#150]
First of all, great work guys! Many thanks for this great software!
I am using it on linux and windows, but i can't get it running on my raspberry pi. Unfortunately, I'm not a programmer, so I can't narrow down the error. 

While compiling the attached error occurred.

I hope you've got an idea, how i can fix it.

Many thanks!
Christian
[compile_error.txt](https://github.com/netheril96/securefs/files/10475015/compile_error.txt)

**Comment by netheril96** [comment]
You can try the latest release with `build.py`.
