### ISSUE TITLE
How to deal with long file names

### ISSUE THREAD

**Issue by maxox** [netheril96/securefs#151]
Just started to use this software, and tried uploading files to my cloud, and realize the encrypted filenames are too long to upload.
So I tried creating a folder named "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII" and realize in this case the encrypted folder name becomes way too long.

Any ideas to deal with such situations? or i just have to rename all my files?

**Comment by netheril96** [comment]
Choice 1: use shorter filenames
Choice 2: create a new repo with command line `--format 2`. This format supports longer filenames, but if you have multiple devices with cloud sync, conflicts will be harder to resolve

**Comment by maxox** [comment]
Sounds great. I'll stick with --format 2 for now, thank you.
