### ISSUE TITLE
希望能帮助完成一些工作

### ISSUE THREAD

**Issue by rongliangtang** [netheril96/securefs#152]
你好，最近学习了您的securefs这个项目，把源码大概过了遍，感觉特别好，学习到了特别多东西。
但是自己没有好的idea来refine这个项目，想请问下这个项目有没有未完成的工作，或者您还未开始的工作，我可以来完成这部分开发。

**Comment by netheril96** [comment]
现在没有什么feature的开发

在[`vcpkg`这个分支](https://github.com/netheril96/securefs/tree/vcpkg)上，我准备用vcpkg管理依赖，而不是现在这样全包在代码里。但是如果用户用了自己的包管理比如homebrew或者apt，我希望这个CMakeLists.txt可以兼容他们，也就是可以disable vcpkg。这是一个繁琐的工作，你要是愿意也可以做。

还有一个，如果你有macbook，可以帮我看看用[fuse-t](https://github.com/macos-fuse-t/fuse-t)没法过[测试](https://github.com/netheril96/securefs/actions/runs/3775515855)。

**Comment by netheril96** [comment]
没有什么exciting的工作要做了

**Comment by rongliangtang** [comment]
好的 我看看

**Comment by rongliangtang** [comment]
没太理解“用fuse-t没法过测试”的意思，您能具体说说吗

**Comment by netheril96** [comment]
你看这个run：https://github.com/netheril96/securefs/actions/runs/3775597110/jobs/6418368995
测试过不了
我现在没有mac了，很难debug这个问题
