### ISSUE TITLE
Add the option to NOT encrypt filenames

### ISSUE THREAD

**Issue by llucps** [netheril96/securefs#155]
Hi,

It would be great if you could add an option where filenames are not encrypted. The same way as Gocryptfs does with:

```
-plaintextnames

Do not encrypt file names and symlink targets.
```

The main reason for having this feature is allowing to synchronize the files in the encrypted volume from all my computers and private server (VPS) using [Unison](https://github.com/bcpierce00/unison).

I can synchronize the files anyway, but it's very convenient to be able to see the files names in case I edited on file from Computer 1 and other files on Computer 2. Then when I sync with my VPS I can know which file are which and decide what needs to be synchronized. 

Thanks.

**Comment by netheril96** [comment]
Added in [0.14.2](https://github.com/netheril96/securefs/releases/tag/0.14.2).

**Comment by llucps** [comment]
Thank you!
