### ISSUE TITLE
CryptoppConfig.cmake not found

### ISSUE THREAD

**Issue by dhammel** [netheril96/securefs#157]
Hello,

When compiling latest version from source, there are missing dependencies. Getting an error of cryptoppConfig.cmake not found. 

libcryptoo++-dev is installed via apt. So it appears the apt related packages are not working.

I found a project here: https://github.com/abdes/cryptopp-cmake

Though im not sure if thats the official one you use, and would rather not install software from unofficial sources.

Do you have a list of requried dependencies, and where I can get them if not from apt? Maybe posting this in the README for other users as well.

I had managed to get it built by vcpkg, however as to avoid using microsoft software or any if possible. I can't seem to get securefs built using system libraries installed via apt.

Thank you!

**Comment by netheril96** [comment]
I'm writing a custom PPA for `securefs`. You can also refer to [this](https://github.com/netheril96/securefs/blob/bce0eae6585810ef5d03becae8ed1dc308ac4ffe/.github/workflows/ccpp.yml#L38).

**Comment by tari3x** [comment]
Is this issue resolved? I'm getting the same error trying to compile current tip.

**Comment by dhammel** [comment]
@tari3x It does not appear to be resolved yet, as of now it seems in can only be compiled using vcpkg.

**Comment by tari3x** [comment]
@netheril96 : could we reopen this issue please?

**Comment by netheril96** [comment]
Please refer to my link in the previous comment if you want to build against system libs

**Comment by tari3x** [comment]
Sorry, I don't understand. I check out with "git clone --recursive" and get a cmake error despite having installed "libcryptopp-devel" (I'm on OpenSuSE). Does this qualify as a problem? 

I see that an older checkout has external/cryptopp and the new one doesn't. Maybe that's the problem?

**Comment by dhammel** [comment]
@tari3x Are you trying to build with vcpkg? I haven't been able to actually get it to build against system libs as of yet.

If you want to build with vcpkg, you do not need to clone recursively as there is no sub modules.

Following is personally tested with Ubuntu

Just clone vcpkg at url: https://github.com/microsoft/vcpkg.git

then clone securefs with url: https://github.com/netheril96/securefs.git

At this point, you can checkout a specific release tag to ensure you build a stable release: git checkout 0.14.2

then just run command inside root of securefs directory: python3 build.py --enable_test --vcpkg="/path/" 

remember to replace /path/ with your vcpkg source directory. You need to of course install python3 if you don't have it already.

Recursively cloning isn't needed any more, as there are no sub modules. My issue on Kubuntu, with building against system libs is that I cannot download a specific package from apt, as it is not available (assuming its not the libcrypto++ one as I've mentioned). Where it was normally provided as a sub module before, which is why I need to wait for developer to create a ppa, if its still being worked on if I wish to avoid building with vcpkg.

**Comment by tari3x** [comment]
I'm trying to build with cmake - does not being able to do so qualify as an issue? If not, should we remove cmake entirely, so people don't waste time trying?

@dhammel : thanks for the instructions, might come in handy! I don't need to compile urgently - old version works, but one day I will have to!

**Comment by dhammel** [comment]
@tari3x The project itself is built around cmake, so thats whats used to build. vcpkg just handles the dependencies, so there are no longer a need to have them as sub modules.

**Comment by netheril96** [comment]
@dhammel Thank you for explaining what I should have said. 

The PPA is in progress.

**Comment by netheril96** [comment]
Let me reopen this thread until the PPA is ready.

**Comment by netheril96** [comment]
Support for certain Linux distros are added in [0.14.3](https://github.com/netheril96/securefs/releases/tag/0.14.3).
