### ISSUE TITLE
I Forgot the password

### ISSUE THREAD

**Issue by uuc110** [netheril96/securefs#159]
how Do i recover my files. I forgot the password? I do have the config file. and salt you know the stuff. Can I recover in anyway?

**Comment by netheril96** [comment]
If you remember something about your password, like it starts with `abc` and is followed by three digits, you can iterate through all possibilities to see if anyone matches. If you don't remember anything, you are out of luck.

**Comment by uuc110** [comment]
> If you remember something about your password, like it starts with `abc` and is followed by three digits, you can iterate through all possibilities to see if anyone matches. If you don't remember anything, you are out of luck.

I have created some possible combination of words using gpt, how can i use it on the text field of SecureFS. I have Microsoft installed Version, can i use something like, installing github release version and then try doing something from terminal .. something like that

**Comment by netheril96** [comment]
> I have Microsoft installed Version, 

I'm curious, what is "Microsoft installed Version" in your words. But the version shouldn't make any difference.

> try doing something from terminal .. something like that

Do you know anything about programming? Just write a for-loop to iterate over all possibilities, and try mount with `securefs`.
