### ISSUE TITLE
Daily use of securefs with Dropbox?

### ISSUE THREAD

**Issue by hanthethanh** [netheril96/securefs#16]
Hi,

I have been looking for a solution to encrypt my dropbox files and found securefs which looks most promising to me. Are there users who use securefs with Dropbox for daily use?

**Comment by netheril96** [comment]
As the author of this program I use it frequently with iCloud Drive. I have little experience with Dropbox, but it should work just the same.

**Comment by hanthethanh** [comment]
thanks for the prompt reply. 

Is it possible to mount a directory simultaneously from multiple hosts?

**Comment by netheril96** [comment]
I don't understand what you mean by "multiple hosts". Can you clarify?

**Comment by hanthethanh** [comment]
I would like to do the following:
- mount ~/Dropbox/encrypted on a mac at home and keep it mounted all the time
- mount ~/Dropbox/encrypted on a linux box at work, without unmounting it on the mac at home

Is it possible?

**Comment by netheril96** [comment]
Sorry, it is not possible due to the fundamental design of `securefs`. You may try your luck with https://github.com/rfjakob/gocryptfs.

**Comment by rprieto** [comment]
Hi, can you clarify why it's not possible due to the design?
Is it because there's a risk of clash if both computers add a file to the same directory, for example?

**Comment by netheril96** [comment]
@rprieto Yes. The directory file will change in both directories and the sync service won't be able to automatically resolve the difference.

**Comment by netheril96** [comment]
A critical security vulnerability has been found in securefs version 0.4.0 to 0.6.0. If you have used these version to encrypt your data, please either migrate to the newest version or some other encryption software.
