### ISSUE TITLE
Crash. libc++abi: terminating due to uncaught exception...

### ISSUE THREAD

**Issue by popflag** [netheril96/securefs#161]
Crash when opening an encrypted document with MS Excel using macOS

Error: libc++abi: terminating due to uncaught exception of type securefs::UTF8ProcException.

**Comment by netheril96** [comment]
Please mount with option `--normalization=none`. And report to me the unencrypted filename of your document, if it is not sensitive.

**Comment by popflag** [comment]
It work.

The file name is a normal Chinese and numbers document, using - as the separator and no other special characters, like `2023xxxx-xxxx.xlsx`.

Is it possible that the problem is caused by a temporary file automatically created by Excel? Something like ~$file-name.xlsx?

**Comment by netheril96** [comment]
Not sure what causes this. In principle, both ASCII and Chinese characters should stay the same after these transformations.

Anyway, I pushed a new commit that no longer throws on such cases.
