### ISSUE TITLE
How to build on Windows?

### ISSUE THREAD

**Issue by s25765** [netheril96/securefs#162]
Hi,
I love this project! It is very useful and thank you for building it!
However, I can't get it to build on Windows. Is there instructions on how to build this project on Windows?
BTW, I successfully got it built on Linux by running build.py, but I can't get build.py running on Windows. I guess on Windows a separate script should be used.
Steve

**Comment by netheril96** [comment]
The script is cross platform. This is the command for GitHub Actions: https://github.com/netheril96/securefs/blob/f86255a8b61e629793da8f4d32b187f9f9420f51/.github/workflows/ccpp.yml#L142

You probably need to add `--triplet=x64-windows-static-md` on Windows.

**Comment by netheril96** [comment]
If it still doesn't work, please post more details like the error message

**Comment by s25765** [comment]
Thank you for your quick response! Now I changed my build command to following:
    python build.py --triplet=x64-windows-static-md --vcpkg_root="c:\GitHub\securefs\vcpkg"

Below is the entire output, the error I got is about "absl".

 C:\GitHub\securefs>python build.py --triplet=x64-windows-static-md --vcpkg_root="c:\GitHub\securefs\vcpkg"
Executing ('cmake', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_TOOLCHAIN_FILE=c:\\GitHub\\securefs\\vcpkg/scripts/buildsystems/vcpkg.cmake', '-DVCPKG_TARGET_TRIPLET=x64-windows-static-md', '-DSECUREFS_ENABLE_UNIT_TEST=OFF', '-DSECUREFS_ENABLE_INTEGRATION_TEST=OFF', 'C:\\GitHub\\securefs')
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Error at CMakeLists.txt:77 (find_package):
  Could not find a package configuration file provided by "absl" with any of
  the following names:

    abslConfig.cmake
    absl-config.cmake

  Add the installation prefix of "absl" to CMAKE_PREFIX_PATH or set
  "absl_DIR" to a directory containing one of the above files.  If "absl"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "C:\GitHub\securefs\build.py", line 99, in <module>
    main()
  File "C:\GitHub\securefs\build.py", line 88, in main
    check_call(*configure_args)
  File "C:\GitHub\securefs\build.py", line 10, in check_call
    subprocess.check_call(args)
  File "C:\Users\h27h2\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('cmake', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_TOOLCHAIN_FILE=c:\\GitHub\\securefs\\vcpkg/scripts/buildsystems/vcpkg.cmake', '-DVCPKG_TARGET_TRIPLET=x64-windows-static-md', '-DSECUREFS_ENABLE_UNIT_TEST=OFF', '-DSECUREFS_ENABLE_INTEGRATION_TEST=OFF', 'C:\\GitHub\\securefs')' returned non-zero exit status 1.

**Comment by netheril96** [comment]
Have you properly installed `vcpkg`? What is the output of `c:\GitHub\securefs\vcpkg\vcpkg.exe version`?

**Comment by s25765** [comment]
I followed instructions on this page: https://github.com/microsoft/vcpkg to install Vcpkg.
Here is what I did:
   1. mkdir c:\src
   2. cd c:\src
   3. git clone https://github.com/microsoft/vcpkg
   4. .\vcpkg\bootstrap-vcpkg.bat
   5. then I used Windows Explorer to move folder c:\src\vcpkg to C:\GitHub\securefs, so it became C:\GitHub\securefs\vcpkg. I guess this step did nothing useful, probably nothing harmful either.
   
Here is the version of vcpkg:

C:\GitHub\securefs>.\vcpkg\vcpkg.exe version
vcpkg package management program version 2023-08-09-9990a4c9026811a312cb2af78bf77f3d9d288416

**Comment by s25765** [comment]
BTW, I saw 'absl' in CMakeLists.txt and 'abseil' in vcpkg.json, are they the same thing? Maybe this is not related to my build issue.

**Comment by s25765** [comment]
NOTES -- I ran vcpkg search commands trying to find abseil and absl. The output of one of those commands says 'Deprecated'.  Here are those two commands:

C:\GitHub\securefs>\src\vcpkg\vcpkg.exe search abseil
warning: The vcpkg C:\src\vcpkg\vcpkg.exe is using detected vcpkg root C:\src\vcpkg and ignoring mismatched VCPKG_ROOT environment value C:\Program Files\Microsoft Visual Studio\2022\Community\VC\vcpkg. To suppress this message, unset the environment variable or use the --vcpkg-root command line switch.
abseil                   20230802.0       an open-source collection designed to augment the C++ standard library.
abseil[cxx17]                             Enable compiler C++17.
stronk[abseil]                            Dependencies for abseil extension
The result may be outdated. Run `git pull` to get the latest results.
If your port is not listed, please open an issue at and/or consider making a pull request.    -  https://github.com/Microsoft/vcpkg/issues

C:\GitHub\securefs>\src\vcpkg\vcpkg.exe search absl
warning: The vcpkg C:\src\vcpkg\vcpkg.exe is using detected vcpkg root C:\src\vcpkg and ignoring mismatched VCPKG_ROOT environment value C:\Program Files\Microsoft Visual Studio\2022\Community\VC\vcpkg. To suppress this message, unset the environment variable or use the --vcpkg-root command line switch.
grpc[absl-sync]                           Deprecated.
The result may be outdated. Run `git pull` to get the latest results.
If your port is not listed, please open an issue at and/or consider making a pull request.    -  https://github.com/Microsoft/vcpkg/issues

**Comment by s25765** [comment]
FYI, I tried installing vcpkg packages by hand, I guess it is not the right thing to do, but here is what I did:

``C:\GitHub\securefs>\src\vcpkg\vcpkg.exe install

  C:\GitHub\securefs>\src\vcpkg\vcpkg.exe install --triplet=x64-windows

  C:\GitHub\securefs>set absl_DIR=C:\src\vcpkg\packages\abseil_x64-windows\share\absl

  C:\GitHub\securefs>python build.py --triplet=x64-windows-static-md --vcpkg_root="c:\src\vcpkg"                                            Executing ('cmake', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_TOOLCHAIN_FILE=c:\\src\\vcpkg/scripts/buildsystems/vcpkg.cmake', '-DVCPKG_TARGET_TRIPLET=x64-windows-static-md', '-DSECUREFS_ENABLE_UNIT_TEST=OFF', '-DSECUREFS_ENABLE_INTEGRATION_TEST=OFF', 'C:\\GitHub\\securefs')    CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):                                                                     Compatibility with CMake < 3.5 will be removed from a future version of                                                                   CMake.                                                                                                                                                                                                                                                                              Update the VERSION argument <min> value or use a ...<max> suffix to tell                                                                  CMake that the project does not need compatibility with older versions.                                                                                                                                                                                                                                                                                                                                                     CMake Error at CMakeLists.txt:77 (find_package):                                                                                            Could not find a configuration file for package "absl" that is compatible                                                                 with requested version "".                                                                                                                                                                                                                                                          The following configuration files were considered but not accepted:                                                                                                                                                                                                                   C:/src/vcpkg/packages/abseil_x64-windows/share/absl/abslConfig.cmake, version: 20230802 (64bit)                                                                                                                                                                                                                                                                                                                                                                                                                                                                     -- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "C:\GitHub\securefs\build.py", line 99, in <module>
    main()
  File "C:\GitHub\securefs\build.py", line 88, in main
    check_call(*configure_args)
  File "C:\GitHub\securefs\build.py", line 10, in check_call
    subprocess.check_call(args)
  File "C:\Users\h27h2\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('cmake', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_TOOLCHAIN_FILE=c:\\src\\vcpkg/scripts/buildsystems/vcpkg.cmake', '-DVCPKG_TARGET_TRIPLET=x64-windows-static-md', '-DSECUREFS_ENABLE_UNIT_TEST=OFF', '-DSECUREFS_ENABLE_INTEGRATION_TEST=OFF', 'C:\\GitHub\\securefs')' returned non-zero exit status 1.

**Comment by s25765** [comment]
The error message I got is "The following configuration files were considered but not accepted:                                                                                                                                                                                                                   C:/src/vcpkg/packages/abseil_x64-windows/share/absl/abslConfig.cmake, version: 20230802 (64bit)                                                                                                                                                                                                                                                                                                                                                                                                                                                                     -- Configuring incomplete, errors occurred!
"

**Comment by netheril96** [comment]
It's obvious that moving vcpkg installation isn't as harmless as you think. You should delete `C:\GitHub\securefs\vcpkg` and reinstall vcpkg without moving this time.

**Comment by s25765** [comment]
Yes I deleted C:\GitHub\securefs\vcpkg and started building vcpkg from scratch under c:\src. Here is the EXE file:

```
C:\src\vcpkg>dir *.exe
 Volume in drive C is Windows
 Volume Serial Number is 1A66-051B

 Directory of C:\src\vcpkg

09/02/2023  01:44 PM         8,566,200 vcpkg.exe
               1 File(s)      8,566,200 bytes
               0 Dir(s)   4,485,623,808 bytes free

C:\src\vcpkg>

```
Unfortunately I still got same build error. I'll continue to troubleshoot it.

Thanks!
Steve

**Comment by netheril96** [comment]
It's also possible that the other installation at `C:\Program Files\Microsoft Visual Studio\2022\Community\VC\vcpkg` is interfering with your current one. Are you building from HEAD of `securefs`? In that case, can you try dropping the argument `--vcpkg_root` and let the build script pick from the environment variable?

**Comment by s25765** [comment]
Good news! It is compiling securefs C++ source code now.
Thank you for your "HEAD of securefs" hint, so I switched to release 0.14.3, now it is compiling btree_dir.cpp.

Error I got now is:

    ```
  btree_dir.cpp
    C:\securefs-0.14.3\sources\platform.h(17,10): fatal  error C1083: Cannot open include file: 'fuse.h': No such file or directory [C:\Users
    \h27h2\AppData\Local\Temp\securefsc50eiee5\securefs-static.vcxproj]

```

It's GREAT progress. Thank you! I'll continue working on it.

**Comment by s25765** [comment]
I'll find out where fuse.h is. I guess a required package didn't get installed.

**Comment by s25765** [comment]
WOW! I got it successfully built!
` Directory of C:\Users\h27h2\AppData\Local\Temp\securefsa90qggwq\Release

09/03/2023  02:31 PM         1,050,112 securefs.exe
               1 File(s)      1,050,112 bytes
`
I reinstalled WinFSP to include developer files (optional), now everything is work!
Thank you for your help! I really appreciate it.
Steve

**Comment by netheril96** [comment]
Congratulations! Thanks for your interest in my software.
