### ISSUE TITLE
Destination Path Too Long

### ISSUE THREAD

**Issue by s25765** [netheril96/securefs#163]
I got error "Destination Path Too Long" using securefs-0.14.3 on Win11 when backing up my encrypted folder. 

Here is what I did:
  1) securefs.exe create Secret
  2) securefs.exe mount Secret Mount
  3) copy source code folder c:\securefs-0.14.3 to Mount folder
  4) kill the running securefs.exe
  5) in Windows File Explorer, select Secret folder, ctrl-c and ctrl-v to make a copy 
  6) then I got the Destination Path Too Long error

I first encountered this error when I was trying to save a copy of my encrypted folder to external USB drive, but then I found out it has nothing to do with another drive, you can easily repro this problem using just internal C drive.

Thanks,
Steve

**Comment by s25765** [comment]
Notes - The longest file name is 344 bytes in length, it is this one:

WJ4842J7A4MPG8MUWEADX87E9INB7NTZPHWFH97THMW6RU9RTI\UIU3WBRI33WY7PNC5MYHFUZPXJR2YYFH\4PVV3X9CSC8TQ92V6K9P4QKGUQTNVBP5A3WFZMD9\923MW76TFVK872VQ8CPSZ3ZUXZJS\23TQRSJ2MV8YN8GIVXN6CXU2666V2\SIVJI5ZDQBEY4UMRM8BFK84SNHPRXD26XXZH2GFUWW\NUVSW6BV7QKUPYGBSAIH5K3UAQSI93X4CN3AVPRUR6PJYGRBSJFNQRTBFUHHNN9JVJWTU75MAJX2EEIXICYSVKSZUBPIESJU6VBZN4HSY3V4UBCJBV2P8

**Comment by netheril96** [comment]
Several options: 

* Switch to format 2 (`securefs create --format 2`).
* Workaround the limitation of Windows Explorer (see https://superuser.com/questions/1783364/still-no-file-paths-longer-than-260-characters-in-win-explorer-in-2023)

**Comment by netheril96** [comment]
Also see [this](https://superuser.com/questions/1476969/windows-10-limits-the-file-names)

**Comment by netheril96** [comment]
Some command line tools are also unrestricted, if you enable long paths support in registry.

**Comment by s25765** [comment]
"securefs create --format 2" works great! Thank you!
