### ISSUE TITLE
Consider not using the string "securefs" in metafiles

### ISSUE THREAD

**Issue by mu-arch** [netheril96/securefs#166]
I don't like tipping off anyone viewing my files that I'm using securefs. I'm sure it's still possible they could figure it out, but I'd rather not have it in plaintext.

**Comment by s25765** [comment]
It would be even better if argon2 dose not appear in the json file.

**Comment by netheril96** [comment]
You can rename the `.securefs.json` file however you like. You can even move it to another location. During mounting, specify the whole path of the file by ` --config` option.

**Comment by netheril96** [comment]
> It would be even better if argon2 dose not appear in the json file.

Knowing argon2 gives the attack little advantage. If anything, deterrence.
