### ISSUE TITLE
Install on Windows

### ISSUE THREAD

**Issue by 6677028** [netheril96/securefs#167]
I can't install it on windows. Can you guide me to do this.
  I have downloaded the securefs-windows-amd64.zip . When I double click on the file securefs.exe, But The securefs doesn't run

**Comment by netheril96** [comment]
You need to install the dependency WinFsp. And this is a command line program that you need to run in CMD.exe or PowerShell. You can try [this](https://mhogomchungu.github.io/sirikali/) if you want a GUI.

**Comment by 6677028** [comment]
I did this (picture) but it still doesn't work.
  I'm not an information technology expert, so I'm not sure if what I'm doing is correct.
[img]https://i.imgur.com/2bhLuyk.png[/img]

**Comment by netheril96** [comment]
You need first run `securefs c YOUR-DIRECTORY-TO-STORE-SECRETS` and then `securefs m YOUR-DIRECTORY-TO-STORE-SECRETS Z:` to mount it to drive Z:.

**Comment by 6677028** [comment]
This is my installer. And I've made it to this step, I don't know how to go next. You can see picture.
`[img]https://i.imgur.com/4Lp37M3.png[/img]`
 I'm sorry I don't know what to do so I asked too many questions.

**Comment by netheril96** [comment]
I see that you may not be familiar with command line. Can you try [this](https://mhogomchungu.github.io/sirikali/) which is a GUI that supports securefs? That is easier to use.

**Comment by 6677028** [comment]
I have installed SiriKali Ok. Now how do I install Securefs
<a href="https://imgur.com/jeSeI10"><img src="https://i.imgur.com/jeSeI10.png" title="source: imgur.com" /></a>

**Comment by netheril96** [comment]
I think there is a setting in menu to set the path of `securefs.exe`.

**Comment by mhogomchungu** [comment]
Latest version of SiriKali can now install/update securefs from within the app and steps to do is are:-
1. Click "Menu" button.
2. Click "Check For Updates" entry on the generated menu.
3. On the  window that will show up. right click "securefs" entry and then click "Update" entry on the generated menu.
4. Restart SiriKali when the update complete.
