### ISSUE TITLE
make mount the default command

### ISSUE THREAD

**Issue by pmazzini** [netheril96/securefs#173]
It would be great to make mount the default command.

This would allow making `securefs` work with `fuse.mount` without having to create a wrapper for it.

```
mount.fuse --help
usage: mount.fuse type#[source] destination [-t type] [-o opt[,opts...]]
```

And in turn it will allow easier integration with `pam_mount` which uses the above syntax.

Thoughts? Thanks

**Comment by netheril96** [comment]
Even if that is possible, you'll still need a wrapper if you want to pass in any securefs specific options, like `--config`, or `--plain-text-names`. So the value of this seems quite small, i.e. applicable only if you want to use `pam_mount` _and_ are satisfied with the default options.
