### ISSUE TITLE
Building securefs on windows

### ISSUE THREAD

**Issue by anubhav6864** [netheril96/securefs#175]
Hi,
 I am trying to build securefs on windows and have also installed `vcpkg`.
As mentioned [here](https://github.com/netheril96/securefs/issues/162#issuecomment-1702372782)
I am running the command `python3 build.py --enable_unit_test --enable_integration_test --triplet=x64-windows-static-md --build_root=./build` and getting the following error:

`Executing ('cmake', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_TOOLCHAIN_FILE=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\vcpkg\\scripts/buildsystems/vcpkg.cmake', '-DVCPKG_TARGET_TRIPLET=x64-windows-static-md', 'C:\\git\\securefs\\securefs')
Traceback (most recent call last):
  File "C:\git\securefs\securefs\build.py", line 118, in <module>
    main()
  File "C:\git\securefs\securefs\build.py", line 107, in main
    check_call(*configure_args)
  File "C:\git\securefs\securefs\build.py", line 11, in check_call
    subprocess.check_call(args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 408, in check_call
    retcode = call(*popenargs, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified`

Any help will be really helpfull.
thanks

**Comment by netheril96** [comment]
You need to make sure `cmake.exe` is in your `PATH`.

**Comment by netheril96** [comment]
By the way, I just had a new release. Please build the new one.

**Comment by anubhav6864** [comment]
After including cmake to PATH getting `vcpkg `related error.
Not sure, why I am getting this as, I have already added the vcpkg to PATH which gets installed with Visual Studio.

C:\git\securefs\securefs>python3 build.py --enable_unit_test --enable_integration_test --triplet=x64-windows-static-md --build_root=./build
Executing ('cmake', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_TOOLCHAIN_FILE=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\vcpkg\\scripts/buildsystems/vcpkg.cmake', '-DVCPKG_TARGET_TRIPLET=x64-windows-static-md', 'C:\\git\\securefs\\securefs')
-- Building for: Visual Studio 17 2022
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Running vcpkg install
error: this vcpkg instance requires a manifest with a specified baseline in order to interact with ports. Please add 'builtin-baseline' to the manifest or add a 'vcpkg-configuration.json' that redefines the default registry.
-- Running vcpkg install - failed
CMake Error at C:/Program Files/Microsoft Visual Studio/2022/Community/VC/vcpkg/scripts/buildsystems/vcpkg.cmake:899 (message):
  vcpkg install failed.  See logs for more information:
  C:\git\securefs\securefs\build\vcpkg-manifest-install.log
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:146 (include)
  CMakeLists.txt:19 (project)


-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "C:\git\securefs\securefs\build.py", line 118, in <module>
    main()
  File "C:\git\securefs\securefs\build.py", line 107, in main
    check_call(*configure_args)
  File "C:\git\securefs\securefs\build.py", line 11, in check_call
    subprocess.check_call(args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('cmake', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_TOOLCHAIN_FILE=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\vcpkg\\scripts/buildsystems/vcpkg.cmake', '-DVCPKG_TARGET_TRIPLET=x64-windows-static-md', 'C:\\git\\securefs\\securefs')' returned non-zero exit status 1.

**Comment by anubhav6864** [comment]
Some more progress, updated the vcpkg manifest.

C:\git\securefs\securefs>python3 build.py --enable_unit_test --enable_integration_test --triplet=x64-windows-static-md --build_root=./build
Executing ('cmake', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_TOOLCHAIN_FILE=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\vcpkg\\scripts/buildsystems/vcpkg.cmake', '-DVCPKG_TARGET_TRIPLET=x64-windows-static-md', 'C:\\git\\securefs\\securefs')
-- Running vcpkg install
All requested packages are currently installed.
A suitable version of 7zip was not found (required v23.1.0) Downloading portable 7zip 23.1.0...
Downloading 7zip...
https://www.7-zip.org/a/7z2301-extra.7z->C:\Users\Anubhav Gupta\AppData\Local\vcpkg\downloads\7z2301-extra.7z
Downloading https://www.7-zip.org/a/7z2301-extra.7z
Extracting 7zip...
Total install time: 5.2 us
-- Running vcpkg install - done
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
-- The C compiler identification is MSVC 19.39.33523.0
-- The CXX compiler identification is MSVC 19.39.33523.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE
CMake Error at C:/Program Files/Microsoft Visual Studio/2022/Community/VC/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package):
  Could not find a package configuration file provided by "absl" with any of
  the following names:

    abslConfig.cmake
    absl-config.cmake

  Add the installation prefix of "absl" to CMAKE_PREFIX_PATH or set
  "absl_DIR" to a directory containing one of the above files.  If "absl"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:75 (find_package)


-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "C:\git\securefs\securefs\build.py", line 137, in <module>
    main()
  File "C:\git\securefs\securefs\build.py", line 124, in main
    check_call(*configure_args)
  File "C:\git\securefs\securefs\build.py", line 12, in check_call
    subprocess.check_call(args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('cmake', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_TOOLCHAIN_FILE=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\vcpkg\\scripts/buildsystems/vcpkg.cmake', '-DVCPKG_TARGET_TRIPLET=x64-windows-static-md', 'C:\\git\\securefs\\securefs')' returned non-zero exit status 1.

**Comment by anubhav6864** [comment]
I believe the `vcpkg` error is gone now.
This is the fresh error:

C:\git\securefs\securefs>python3 build.py --enable_unit_test --enable_integration_test --triplet=x64-windows-static-md --build_root=./build --vcpkg_root="C:\git\securefs\vcpkg"
Executing ('cmake', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_TOOLCHAIN_FILE=C:\\git\\securefs\\vcpkg\\scripts/buildsystems/vcpkg.cmake', '-DVCPKG_TARGET_TRIPLET=x64-windows-static-md', 'C:\\git\\securefs\\securefs')
-- Running vcpkg install
All requested packages are currently installed.
Total install time: 1.1 us
-- Running vcpkg install - done
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
CMake Error at C:/Program Files/Microsoft Visual Studio/2022/Community/VC/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package):
  Could not find a package configuration file provided by "absl" with any of
  the following names:

    abslConfig.cmake
    absl-config.cmake

  Add the installation prefix of "absl" to CMAKE_PREFIX_PATH or set
  "absl_DIR" to a directory containing one of the above files.  If "absl"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:75 (find_package)


-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "C:\git\securefs\securefs\build.py", line 137, in <module>
    main()
  File "C:\git\securefs\securefs\build.py", line 124, in main
    check_call(*configure_args)
  File "C:\git\securefs\securefs\build.py", line 12, in check_call
    subprocess.check_call(args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('cmake', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_TOOLCHAIN_FILE=C:\\git\\securefs\\vcpkg\\scripts/buildsystems/vcpkg.cmake', '-DVCPKG_TARGET_TRIPLET=x64-windows-static-md', 'C:\\git\\securefs\\securefs')' returned non-zero exit status 1.

**Comment by anubhav6864** [comment]
In the Readme file it is mentioned to run `python3 build.py --enable_unit_test` for building but when I run it I get `ValueError: Cannot find vcpkg installation by heuristic. Please specify --vcpkg_root explicitly.`

**Comment by netheril96** [comment]
>  Can you please elaborate more on how changing .securefs.conf would affect the working?

The new config has more things encrypted, and has support for filename longer than 143 bytes (also in the release notes).

**Comment by anubhav6864** [comment]
Is there a way we can see the contents of config file in plain text?
