### ISSUE TITLE
Mounting over the same directory makes the securefs hang

### ISSUE THREAD

**Issue by mdarse** [netheril96/securefs#18]
I tried to mount an encrypted file system using this command:
```
$ securefs mount ~/Secret ~/Secret
```
This causes the process to hang, the Terminal with it, and any process trying to list the `~` directory.
Does securefs use the high-level fuse API that returns file path instead of inodes? This may be the reason of the deadlock, causing recursing again and again, but I may be wrong.

**Comment by netheril96** [comment]
What is the operating system and the version you are using?

**Comment by mdarse** [comment]
Oops sorry, I forgot that part 😬

I'm running Mac OS X `10.9.5` with FUSE for OS X in version `3.5.2`.
securefs is in version `0.5.4` (built from source with homebrew).

**Comment by mdarse** [comment]
Just updated to FUSE `3.5.3`, with the same issue 😭

**Comment by netheril96** [comment]
The reason for this is that Mac OS X Mavericks does not have `openat`, `unlinkat` and `mkdirat`. `securefs` emulates these syscalls on these older systems but the emulation cannot handle recursion as you have seen. It cannot be fixed due to the limitations of the operating system.

On OS X El Capitan or Linux, mounting over the same directory works just fine. I think that it works on Yosemite as well, but have not tested it.

**Comment by mdarse** [comment]
Mmh, I see.
So basically when `openat` is not available, you convert the path to an absolute one with `norm_path` and pass this to `open`.
Since the issue is to have absolute directory in this case, would it be possible to use `fchdir` before the mount to change the cwd to the underlying FS location, and just pass a relative path to `open` after that?

**Comment by netheril96** [comment]
`fchdir` changes the working directory process wide and may interfere with subsequent file system operations.

May I ask why you find mounting over the same directory a necessary functionality?

**Comment by mdarse** [comment]
The idea is to have encrypted home directory, where it's not possible to change the location of the directory easily. Ideally, I would like to have a PAM module doing the mount on login. I want functionality similar to PEFS (FreeBSD only), but on macOS. I think it will be too much work to port the filesystem to Darwin so I am trying alternate solutions.

**Comment by netheril96** [comment]
`securefs` performs not very well in case of large amount of small files, which may be the case when your home directory contains source codes.

**Comment by netheril96** [comment]
Running `make` on a `securefs` volume may be very slow.

**Comment by mdarse** [comment]
From what I found, `securefs` doesn't perform that bad https://nuetzlich.net/gocryptfs/comparison/ (go to "Performance"). But thanks for the tip 👍

**Comment by netheril96** [comment]
Anyway, if you really need this functionality, you can just upgrade Mavericks.

**Comment by netheril96** [comment]
A critical security vulnerability has been found in securefs version 0.4.0 to 0.6.0. If you have used these version to encrypt your data, please either migrate to the newest version or some other encryption software.
