### ISSUE TITLE
The application doesn't even work.

### ISSUE THREAD

**Issue by FlawlessCasual17** [netheril96/securefs#182]
Here's the proof:
![(WindowsTerminal)V8r3Y4_05-27-2024](https://github.com/netheril96/securefs/assets/101912712/f59bc633-5f39-4ce6-af59-f768eb70bbc1)

**Comment by netheril96** [comment]
Have you installed WinFsp? What OS and version do you have?

**Comment by netheril96** [comment]
I'm assuming it's a Windows. But what version?

**Comment by FlawlessCasual17** [comment]
> Have you installed WinFsp? What OS and version do you have?

When I made this issue I did not have that installed at the time. I installed it for Cryptomator though. I'll reinstall it and see if having winfsp solves my problem.

> I'm assuming it's a Windows. But what version?

Windows 11

**Comment by FlawlessCasual17** [comment]
Ok, it now works (only with WinFSP):
![image](https://github.com/netheril96/securefs/assets/101912712/20f1d46b-9d4a-487e-8515-a9e56b4689c4)
