### ISSUE TITLE
--reverse?

### ISSUE THREAD

**Issue by greyltc** [netheril96/securefs#19]
encfs has [a feature, `--reverse`](https://github.com/vgough/encfs#reverse-mode) which is very useful for for making encrypted backups to cloud storage providers.

Is there anything like that here?

**Comment by netheril96** [comment]
secures has a rather complex design to ensure heightened security for file names. The design makes reverse mapping practically impossible. I may implement it when securefs adds an optional simpler format.

**Comment by netheril96** [comment]
On second thought, maybe it is doable, as long as the memory is large enough for all the metadata.

**Comment by netheril96** [comment]
However, each time you do a reverse mount, the content and directory structure of the encrypted view will change completely, so incremental backups won't be possible.

**Comment by netheril96** [comment]
A critical security vulnerability has been found in securefs version 0.4.0 to 0.6.0. If you have used these version to encrypt your data, please either migrate to the newest version or some other encryption software.
