### ISSUE TITLE
Permission denied when using minidlna with securefs

### ISSUE THREAD

**Issue by francarl** [netheril96/securefs#191]
OS: Debian GNU/Linux 12 (bookworm)
Platform: WSL2

Hi,
I've mounted a private folder to /media/Y and can access it normally without problem.

```
securefs c SecretFolder
securefs m -b SecretFolder/ /media/Y
ls -l
drwxr-xr-x 2 debian debian 4096 Sep 22 13:01 Y

```
But when I tried to use /media/Y as media folder for minidlna server, I've got this error:

`Restarting DLNA/UPnP-AV media server: minidlna[2024/09/22 13:15:04] minidlna.c:670: error: Media directory "/media/Y" not accessible [Permission denied]`

Any ideas on how to solve this? Thanks.

**Comment by netheril96** [comment]
Is minidlna running as the same user as `securefs` process?

**Comment by francarl** [comment]
Sorry, my fault, users were different! thank you.
