### ISSUE TITLE
Confusion about the full format directory entry

### ISSUE THREAD

**Issue by rongliangtang** [netheril96/securefs#192]
Why not use a B+ tree to store directory entries?

Have you tried other data structures?

**Comment by netheril96** [comment]
The full format does use a B+ tree.

**Comment by rongliangtang** [comment]
Now the full format uses B-tree instead of B+ tree.

**Comment by netheril96** [comment]
Ah, you are correct. But I don’t want to spend the time implementing B+ tree now. It has barely any advantage over existing implementations because the bottleneck of performance is not there.
