### ISSUE TITLE
Is there any way to restore accessibility?

### ISSUE THREAD

**Issue by realwyz** [netheril96/securefs#193]
Hello, is there any way, like a recovery key, to reset the password and keyfile?

Imagine an encrypted dir didn't been used for months or years, then you forgot the password, lost or modified the keyfile, that  could be a disaster!

A recovery key might reduce security, but what if those files don't need that high level of security?

**Comment by netheril96** [comment]
If you save your recovery key safely, why will you lose your password or keyfile? These are equivalent to each other.

The concept of recovery key is only meaningful for logging into online services.

**Comment by realwyz** [comment]
The recovery key is not equal to the password, cause a password can be dynamically computed and only the computation factors are saved, but one may forget to write down the new factors.

**Comment by netheril96** [comment]
Regardless of how you do it, saving the recovery key has exactly the same security and availability characteristics as saving the password or keyfile itself. There is no advantage at all.

**Comment by realwyz** [comment]
The recovery key is stored in an encrypted zip archive and its password is kept by the password manager, which is protected by its master key. Most importantly, there is no record identifying the correspondence, only a list of recovery keys in the zip, but nobody knows which ones are obfuscated or legitimate. I've only used recovery keys once in the last three to four years, trying them out one by one. I bring this up because cryptomator has this feature, and with a new computer, I'd like to try a new solution.

**Comment by netheril96** [comment]
I still don't see the value in this. You can put your password in an encrypted zip archive too, and there is no record identifying the correspondence. Being a "password" doesn't require it to be stored in a password manager. Maybe what you want is multiple password feature, so each of them can be stored in a different way.

**Comment by realwyz** [comment]
The zip archive should never be used unless it's the last hope. The vault passwords I kept changing at least once a year, and they are dynamically computed results. I could just keep the results in a password manager, like the website accounts. All my website accounts' passwords are auto generated by a password manager, if they are corrupted, I could easily reset them through the official email account. But what if the vault dirs' passwords are corrupted? That means I lost all the data!
