### ISSUE TITLE
Please add an explicit warning for cloud services to README.md

### ISSUE THREAD

**Issue by mologie** [netheril96/securefs#20]
Hello,

this is a fascinating project and implementation, but I've just wasted two hours setting it up and debugging an issue for what turned out to be something that was by design. As it turns out, securefs does not fit my use case.

In README.md, "efficient cloud synchronization" is advertised.

I had assumed that I was able to use securefs with synchronized directories such as Dropbox or iCloud Drive on multiple machines at once (because that's what cloud sync is primarily used for.) However, I only later found out that, by design, this is not possible. The comparison to encfs, where this use case is possible, does not mention the issue either.

I'm raising this ticket to kindly ask you to add a big and obvious note to README.md mentioning how and why the user must take care of ensuring that the encrypted storage is never written to simultaneously by multiple machines, or data may go missing.

**Comment by netheril96** [comment]
I am aware of the problem and plan to add explicit file locking to prevent the users from having multiple securefs instances on the same synchronized directory over different machines. I also plan to change the default format to allow your use case.

**Comment by netheril96** [comment]
You are right about how it is important for multiple machines to run securefs simultaneously. I only use cloud services as backups so I didn't design for such use cases initially.

**Comment by mologie** [comment]
Thank you for the quick response(s)! I was not criticising the design, but appreciate that you consider the additional use case. Your project is the only one that, in terms of technology, works on all the 3 major platforms. gocryptfs doesn't run well on Windows and Linux, ecryptfs runs on Linux only, and encfs is ensure.

What my ticket was about is that this design choice is not obvious to the user. Especially so since cloud services are mentioned explicitly.

Not knowing about the current limitation may result in loss of data. Please make it visible/obvious until the necessary changes are made.

**Comment by netheril96** [comment]
By the way, you can recover your data with `securefs fix`, if the losses are not just test data.

**Comment by netheril96** [comment]
The new format has become stable. You can test it now by building from the latest master commit. I will release in a few days.
