### ISSUE TITLE
Cannot create/copy files using Finder, 'out of disk space'

### ISSUE THREAD

**Issue by mologie** [netheril96/securefs#22]
This issue affects the current master branch.

The symptom is that any copy operation using Finder or another Apple-native file UI is stopped with an 'out of disk space' error.

I assume that this is caused by the FUSE-mounted drive showing up as having zero bytes free and total space. Finder appears to use these numbers to prevent starting a file copy operation which is guaranteed to fail.

Creating files via Terminal works as expected.

**Comment by netheril96** [comment]
Yeah, I implemented the `statfs` call but did not add it to the callbacks. Fixed in 7e49934bb7680c6ba375234460271dbdccd7525e.

**Comment by netheril96** [comment]
I am going to tweak the new format in the unreleased version. Please backup your data.

**Comment by netheril96** [comment]
A critical security vulnerability has been found in securefs version 0.4.0 to 0.6.0. If you have used these version to encrypt your data, please either migrate to the newest version or some other encryption software.
