### ISSUE TITLE
Format advice required

### ISSUE THREAD

**Issue by Achim16** [netheril96/securefs#26]
firstly, greatly appreciated that securefs is , so to say, several formats, cryfs-style and encfs under one hood.
can you however please advise on the full format, it's stated on the website that "To request full format, which is no longer the default, run securefs create --format 2.".
I would have thought that format version 3 should be the most evolved b-tree format ?
I also understand that versions >0.7.0 support reading format 1-3 created by old versions affected by security flaws (with the bug just reported fixed), but therefore e.g version 0.5.4 cannot mount format 3 created by version >=0.7.0 (InvalidArgumentException: Unsupported version 3) - correct ? 
So in effect it appears that format 1-3 are now more format subversions like 1.1 etc and in this case would suggest to introduce such kind of numbering.

**Comment by netheril96** [comment]
The format numbers are chronologically numbered. It doesn't mean that 3 is better than 2 or 1. Concretely, the difference between 3 and 2 is that 3 stores the timestamps (access time, mod time, inode time and birth time) encrypted in the meta file, while 2 just let the underlying file system handles them. 3 has larger overhead, so not recommended for average users, unless they have those specific needs.

**Comment by netheril96** [comment]
> So in effect it appears that format 1-3 are now more format subversions like 1.1 etc and in this case would suggest to introduce such kind of numbering.

If designed from scratch, those would be the numbers. Now I have to maintain backwards compatibility.

**Comment by netheril96** [comment]
The file system format with a given version never change. The vulnerability is with key generation.

**Comment by Achim16** [comment]
Thanks for pointing out, clear now to me
