### ISSUE TITLE
Feature suggestion : option "info"

### ISSUE THREAD

**Issue by Achim16** [netheril96/securefs#27]
Can I suggest to introduce an info option like encfsctl does, stating for a filesystem what format was used ,created by which version and also some info about encryption settings used. 
I appreciate that some of the information can be found in the .json file, however I guess such an option would add more transparency eg. on the formats (see prev. post) and also generally.

Thanks
[edit : could also be useful for frontends like Sirikali (->properties) in which this currently works for eCryptFS]

**Comment by netheril96** [comment]
A verbose option will be added

**Comment by netheril96** [comment]
Added in 412d257d400ca3ede3e8f3cc9cc1c7067410f484. If you think more information should be output in verbose logging, please elaborate.

**Comment by Achim16** [comment]
Thanks for that, for sure already an inmprovement. I may have used however the wrong terminology "option" in my original email, it shoud have been "subcommand" , usage eg. securefs info <data dir>, i.e without mounting the folder similiar to what "encfsctl info <root dir>" offers. I for instance much appreciate the "version" subcommand showing hardware features and experience that often more information is better.

**Comment by netheril96** [comment]
In that case, catting the json file should be enough.

**Comment by Achim16** [comment]
Of course your decision as the developer, last argument from my side would be your own presentation of securefs as an alternative to other solution, "securefs is intended to make the experience as smooth as possible" ;-). Yes, like with the hardware flags the information is indeed stored _somewhere_ else, but you wouldn't expect an average user to figure out where this information is stored and to cat .securefs.json (yes, luckily in plain text in contrast to cryfs  but hidden by default) but offer this as a subcommand, this also in the light that the used cipher may in the future become variable, if I understood the remark "currently AES256-GCM" correctly.

**Comment by netheril96** [comment]
Info subcommand added in f4115cf

Here is a sample output

> Config file path: /Users/rsy/icloud/enc/.securefs.json
> Filesystem format version: 4
> Is full or lite format: lite
> Is underlying directory flattened: false
> Is multiple mounts allowed: true
> Is timestamp stored within the fs: false
> 
> Content block size: 4096 bytes
> Content IV size: 96 bits
> Password derivation algorithm: PBKDF2-HMAC-SHA256
> Password derivation iterations: 856064
> Per file key generation algorithm: AES
> Content cipher: AES-128-GCM
>

**Comment by Achim16** [comment]
Tried it, looks great. Thanks a lot

**Comment by mhogomchungu** [comment]
git version of SiriKali now has support for the "info" command.

![screenshot_20170222_225204](https://cloud.githubusercontent.com/assets/3496115/23229504/9f7e36c8-f951-11e6-80d5-7eaabca65e5d.png)
