### ISSUE TITLE
add ability to create/unlock a volume using a key and a keyfile.

### ISSUE THREAD

**Issue by mhogomchungu** [netheril96/securefs#28]
SiriKali can manage securefs volumes using a key and a keyfile since it generates the effective key by itself and then passes on the result to securefs.

The above creates a problem if a user tries to unlock the volume independently of SiriKali and it will be best if securefs also has this ability.

Proposed solutions.
1. An option to use a Key. This already works.
2. An option to use a keyfile.
3. An option to use a combination of a key and a keyfile with the effective key generated with the below formular: key = hmac(sha256,password,keyfile)

**Comment by netheril96** [comment]
Do you just pipe the raw bytes to `securefs`? `securefs` truncates the password before the first carriage return or line feed (and in some versions, null), and that will be a problem if raw bytes are piped.

I plan to change this in the next release, when `securefs` detects that `stdin` is not a tty, accept all data until EOF. That will break backwards compatibility if one uses non-ASCII passwords.

**Comment by mhogomchungu** [comment]
Yes,SiriKali currently just reads the contents of a keyfile and passes them along to securefs but it refuses to do so when it detects a new line character in the keyfile[1]. The git version refuses to proceed,released versions just warned about the potential problem.

I am aware of the problematic nature of having a new line character in the middle of a password and this is why SiriKali checks for this specifically.

I can understand the problem with having a null character in the middle of the password since its presence could trip code that checks the size of the password by looking for the first occurrence of a null character. Will add a check for this in SiriKali.

I do not understand the problem with carriage return character. Why do you treat it as a mark for the end of the password? Under what circumstance will anybody send it as a mark for the end of the input?

[1] https://github.com/mhogomchungu/sirikali/blob/caae18881e5346b52d5f4f2589304e84a96cf14a/src/keydialog.cpp#L859

**Comment by netheril96** [comment]
On second thought, I abandon the idea of raw bytes as passwords. It confuses the user when he/she cannot enter the password interactively.

'\r' signals termination because I also support Windows, and I am not sure if it will always translate carriage return.

**Comment by mhogomchungu** [comment]
SiriKali will now display the below error when it encounters a keyfile with "illegal" characters.

"HMAC+KeyFile" creates a hash of a keyfile using an empty password and a formula in the first comment here.

![screenshot_20170215_125409](https://cloud.githubusercontent.com/assets/3496115/22969366/5fb13644-f37f-11e6-904b-7b171857db16.png)

**Comment by netheril96** [comment]
The keyfile or hmac are just alternative options to generate the password. Nothing inherently different about them warrants integration with `securefs`. The user can just pipe or redirect the keyfile into `securefs` on the command line, or do the key generation with any method he/she so chooses. Integration will be a violation of separation of concerns.

If SiriKali worries that users may need to mount without SiriKali, it should provide an option to export the generated (effective) password.

**Comment by netheril96** [comment]
I have a change of heart now. The separation of concerns is good on Unix, but not so on Windows where there is no program to compute hashes out of the box. The concern now, however, is that I may break SiriKali's compatibility if I add an incompatible way of interpreting keyfile.

**Comment by netheril96** [comment]
So if I were to add an option to use key file incompatible with current SiriKali schemes, how would you present that option in SiriKali?

**Comment by mhogomchungu** [comment]
I would add an option that says something like "securefs keyfile".

**Comment by netheril96** [comment]
Key file is now supported.

**Comment by mhogomchungu** [comment]
Git version of SiriKali now supports securefs keyfile

Below is a new GUI options when creating a volume.

![Screenshot_20200411_101930](https://user-images.githubusercontent.com/3496115/79037976-56f3dd00-7bde-11ea-9eab-c8b5719db976.png)

Below is a new GUI options when unlocking a securefs volume.

![Screenshot_20200411_101959](https://user-images.githubusercontent.com/3496115/79037992-7ab72300-7bde-11ea-8271-dccb6b74a9c4.png)
