### ISSUE TITLE
Cannot enter input after data vulnerability warning message

### ISSUE THREAD

**Issue by denispol** [netheril96/securefs#30]
As I tried to open with the latest build a securefs volume made with a previous version on macos Sierra, I get this message:

```
[Warning] [0x7ffff1c943c0] [2017-02-22 22:36:44.926599000 UTC]    Your filesystem is created by a vulnerable version of securefs.
Please immediate migrate your old data to a newly created securefs filesystem,
and remove all traces of old data to avoid information leakage!
```

I am unable to enter any input, the message asking for input displays and the app immediately quits, leaving me no chance to answer.

`Do you wish to continue with mounting? (y/n)MBPsolid:~ user$`

**Comment by netheril96** [comment]
Have you tried the 0.7.1 release?

**Comment by denispol** [comment]
I actually used homebrew to download securefs, I thought it was retrieving the latest version from GitHub before building it, thus I downloaded and built it myself. It now works like a charm!

**Comment by netheril96** [comment]
You can use homebrew for the latest version. Just pass the option `--HEAD`
