### ISSUE TITLE
Decryption fails in 0.7.1 format 4

### ISSUE THREAD

**Issue by Achim16** [netheril96/securefs#31]
I'm encountering decryption failure in 0.7.1 format 4 (format 2 works with the same files and folders)  on Linux/Debian 8 based
Here's the linux (ext3 fs) process : 
Basically a /test/test source is created (755) , then mounted to ~/secfs - fine.
One file (doublecmd) copied to ~/secfs. fine.  The encrypted content appears as expected in /test/test with approx the same file size - fine I at first sight.
Copying back the file from ~/secfs to plain folder /test/uu (755) fails. 
Log file  :
[Info] [0x7f770308f700] [2017-02-23 01:30:01.886835802 UTC]    init
[Error] [0x7f770208d700] [2017-02-23 01:30:23.194514718 UTC]    chmod path=/doublecmd encounters exception securefs::POSIXException (code=95): Die Operation wird nicht unterstützt (chmod /test/test/ENXU72UM4EJARGK2RGFDCIU7HWGZ4C8ZBJ6XSHWC with mode=0100755)
[Error] [0x7f770208d700] [2017-02-23 01:30:56.496889264 UTC]    read path=/doublecmd offset=131072 length=131072 encounters exception securefs::LiteMessageVerificationException (code=1): File content has invalid checksum
[Error] [0x7f770308f700] [2017-02-23 01:30:56.496927712 UTC]    read path=/doublecmd offset=262144 length=131072 encounters exception CryptoPP::AuthenticatedSymmetricCipher::BadState (code=1): AES/GCM: TruncatedFinal was called before setting key and IV
[Error] [0x7f770308f700] [2017-02-23 01:30:56.499519217 UTC]    read path=/doublecmd offset=393216 length=131072 encounters exception securefs::LiteMessageVerificationException (code=1): File content has invalid checksum
[Error] [0x7f770288e700] [2017-02-23 01:30:56.499548316 UTC]    read path=/doublecmd offset=262144 length=4096 encounters exception CryptoPP::AuthenticatedSymmetricCipher::BadState (code=1): AES/GCM: TruncatedFinal was called before setting key and IV
[Info] [0x7f77044f6740] [2017-02-23 01:31:19.076682546 UTC]    destroy

First thought this was related to access rights, but as I wrote it works using format 2 and also fails using a similar  test on an NTFS partition.

**Comment by netheril96** [comment]
It reads like a concurrency bug. Could you test with mount option `--single`?

**Comment by netheril96** [comment]
A possible fix in d671274.

**Comment by Achim16** [comment]
ok, let's have a look. Procedure for all tests except (4) is the same : Clean prev tests, creation, mount, copy to mounted folder, copy from mounted folder.

1) pre-release 6ed54c3 , format 4, single. Seems to work, I have added an md5 to check integrity,
is ok on the mounted folder and after copying to /test/uu

2) d671274 , format 4, single. same as above, works on the surface log shows errors though
Info] [0x7f520d216740] [2017-02-23 10:17:42.776038763 UTC]    init
[Error] [0x7f520d216740] [2017-02-23 10:18:08.918539583 UTC]    chmod path=/doublecmd.md5 encounters exception securefs::POSIXException (code=95): Die Operation wird nicht unterstützt (chmod /test/test/6S5ME5BR9BAEENSEJV6F8ZE5WDCYKMMRUFFNDXU39UVTE8A with mode=0100644)
[Error] [0x7f520d216740] [2017-02-23 10:18:09.114136817 UTC]    chmod path=/doublecmd encounters exception securefs::POSIXException (code=95): Die Operation wird nicht unterstützt (chmod /test/test/U9355WCSEBE8WMRQ5TQIFMEYETAZIGNHHZWBGF8J with mode=0100755)
[Info] [0x7f520d216740] [2017-02-23 10:18:42.932013069 UTC]    destroy

3) d671274 , format 4, without single option.Copying back  still fails , only part of the file is copied.
MD5 check on the mounted folder produces either a checksum error or access violation of doublecmd.

[Info] [0x7f9e2527f700] [2017-02-23 10:21:02.453291126 UTC]    init
[Error] [0x7f9e2527f700] [2017-02-23 10:21:36.831987383 UTC]    chmod path=/doublecmd.md5 encounters exception securefs::POSIXException (code=95): Die Operation wird nicht unterstützt (chmod /test/test/Y6CJKXD7I6IQV4FA9SUYCJYSR8CXTTD9HGAVTTRGZ3BB2X2 with mode=0100644)
[Error] [0x7f9e24a7e700] [2017-02-23 10:21:37.056162323 UTC]    chmod path=/doublecmd encounters exception securefs::POSIXException (code=95): Die Operation wird nicht unterstützt (chmod /test/test/YUEEAWKFRFSFA2IC8NU7GCE222NFYNQ85IGMRSDX with mode=0100755)
[Error] [0x7f9e1ffff700] [2017-02-23 10:21:58.504420158 UTC]    read path=/doublecmd offset=131072 length=131072 encounters exception CryptoPP::AuthenticatedSymmetricCipher::BadState (code=1): AES/GCM: TruncatedFinal was called before setting key and IV
[Error] [0x7f9e24a7e700] [2017-02-23 10:21:58.504641441 UTC]    read path=/doublecmd offset=262144 length=131072 encounters exception CryptoPP::AuthenticatedSymmetricCipher::BadState (code=1): AES/GCM: TruncatedFinal was called before setting key and IV
[Error] [0x7f9e1f7fe700] [2017-02-23 10:21:58.507524001 UTC]    read path=/doublecmd offset=262144 length=4096 encounters exception securefs::LiteMessageVerificationException (code=1): File content has invalid checksum
[Error] [0x7f9e1effd700] [2017-02-23 10:21:58.507551626 UTC]    read path=/doublecmd offset=393216 length=131072 encounters exception CryptoPP::AuthenticatedSymmetricCipher::BadState (code=1): AES/GCM: TruncatedFinal was called before setting key and IV
[Info] [0x7f9e266e4740] [2017-02-23 10:22:11.040470099 UTC]    destroy


 4) If I just take test (3) and mount using single option, the md5 check on the mount works, means that the initial encryption in (3) seems to have worked.

**Comment by netheril96** [comment]
OK, it seems that there are two different problems.

On this

> chmod path=/doublecmd.md5 encounters exception securefs::POSIXException (code=95): Die Operation wird nicht unterstützt (chmod /test/test/Y6CJKXD7I6IQV4FA9SUYCJYSR8CXTTD9HGAVTTRGZ3BB2X2 with mode=0100644)

So what do you get when you manually run `chmod` on `/test/test/Y6CJKXD7I6IQV4FA9SUYCJYSR8CXTTD9HGAVTTRGZ3BB2X2` or other files under `/test/test/`?

**Comment by netheril96** [comment]
The error messages also don't make sense. 

* Why does a `chmod` call precede the copy? If you copy from `~/secfs`, the file inside `~/secfs` shouldn't have their mode changed, should it?
* How could a `chmod` ends in a `ENOTSUP` error?
* The `TruncatedFinal was called before setting key and IV` can only happen if race conditions occur (is it?), but all the read operations are locked.

(By the way, format 1,2,3 always run single threaded, and they implements their own permission system, so they are not affected at all)

I can't reproduce your issue on a Debian 8.7.1 amd64 on an ext3 partition. To further investigate, I need to way to reproduce it on my (virtual) machine. Please specify the details as much as possible so that I can setup an environment close to yours.

In addition, you may mount with option `--trace`, which will enable a lot of log messages about the internal operations of `securefs`. That may provide more hints to the root cause of the problem.

**Comment by Achim16** [comment]
The environment is on a multiboot system a Debian jessie based LMDE2 installation : 
Host: lmde2 Kernel: 3.16.0-4-amd64 x86_64 (64 bit) Desktop: MATE 1.16.1  Distro: LinuxMint 2 betsy 
To prevent any obstacles, new tests of today happen all inside home of ordinary user , source dir ~/test , mount dir ~/Sirikali/securefs, copy-to-dir ~/uu. Password chosen : test
Permissions on doublecmd 755, doublecmd.md5 644
Operations using pre-release 0.7.1:
securefs c ~/test
securefs m --log ~/test.log --trace ~/test ~/SiriKali/securefs/
via caja : copy doublecmd and doublecmd.md5 to ~/SiriKali/securefs/
via caja : copy doublecmd and doublecmd.md5 from ~/Sirikali/securefs to ~/uu

(I did the copying steps also using cp and further to mount all commands sudo'd , does not change results) 

After the weekend I'll give this a try also on my ubuntu 16.04 , mint 18.1 partitions.
I uploaded the traced log file

[test.log.txt](https://github.com/netheril96/securefs/files/799091/test.log.txt)

**Comment by netheril96** [comment]
Thanks for your patience in helping me with this nasty bug. It is likely due to my misunderstanding on how file locks work. Here is another possible fix in a new branch `fix31` (commit 52ba9b0088c215de344df8621b7241597346ad05)

**Comment by netheril96** [comment]
Scratch that branch. It is too complicated and therefore slow. Please test if the latest master branch has fixed your problem. Thanks!

**Comment by Achim16** [comment]
This seems to work (0.7.2), no errors so far, md5 in ~/uu also verified as ok. As I'm currently doing the test on a USB Stick bootable copy of the above system on a laptop, I'll check this tomorrow on the AMD eight-core as well.
CPU~Dual core Intel Core i7-2620M (-HT-MCP-) clocked at Min:799.980Mhz Max:800.613Mhz Kernel~3.16.0-4-amd64 x86_64 Up~31 min Mem~699.8/7915.4MB HDD~175.6GB(4.9% used) Procs~281 Client~Shell inxi~2.1.28

**Comment by Achim16** [comment]
The results still look promising. Version 0.7.2 used to mount on the original system :
./securefs m --log ~/test.log.txt --trace ~/test ~/SiriKali/securefs/

 with the .json created last week and following operations described above returns no errors on the surface (i.e in caja) and is giving the correct md5 after copying back to plain dir ~/uu
You may want to check however the tracelog attached, it still shows two errors on chmod.
[test.log.txt](https://github.com/netheril96/securefs/files/804143/test.log.txt)

**Comment by netheril96** [comment]
The `chmod` is a separate issue. It is maybe due to a bug in glibc's implementation of `fchmodat`. The master branch has been updated with a possible workaround. Please test.

**Comment by Achim16** [comment]
Still two errors, but returning 'function not implemented' instead of 'operation not supported'.
As usual trace log attached 
[test.log.txt](https://github.com/netheril96/securefs/files/805321/test.log.txt)

**Comment by netheril96** [comment]
OK, so the ext3 filesystem does not support changing mode on symbolic links. New attempt at workaround has been pushed to the master branch.

**Comment by Achim16** [comment]
This seems to have worked, no errors anymore.
[test.log.txt](https://github.com/netheril96/securefs/files/805947/test.log.txt)

**Comment by netheril96** [comment]
Thanks for your help! I think I need to make a new release now.
