### ISSUE TITLE
Q: Dependency of compiled securefs on the host hardware

### ISSUE THREAD

**Issue by Achim16** [netheril96/securefs#34]
This observation is more a question to gain a deeper understanding than an issue :
Case 1:
I'm usually compiling&running securefs  in lmde2 on a physical machine (AMD FX CPU).
Then I did a backup of the above OS using fsarchiver. 
The backup was then "installed" on a laptop (i5 m520 CPU) in a virtual machine (vbox, host OS Ubuntu).
Both CPUs have the same hardware features (securefs version)
Securefs unlike other programs no longer works but fails with 'invalid machine command' - in order to get it running I need to compile it again in the VM and copy to /usr/local/bin. 

Case 2: I also noticed that I can't just on the same physical machine  copy the compiled securefs say from lmde2 to Ubuntu although it's both 64-bit architecture. 

With regard to case 2, I was thinking that this is further to different libs installed, but I'm clueless why this is happening in case 1, the compiled executable seems to be tailored to the individual architecture.

So, the question is can there sth be specified to compile a more "generally" working securefs . executable. 

Thanks

**Comment by netheril96** [comment]
Yes. You can manually build with `cmake -DPORTABLE_BUILD=ON`. That will result in an executable independent of the specific architecture.

By tailoring to the current CPU, the library `crypto++` powering the encryption and decryption can take advantage of instructions such as AES-NI and CLMUL, resulting in double or triple speed up of common operations. A portable build will be much slower, if your CPU has such instructions.

A saner approach would be always compiling those hardware accelerations into the resulting executable, and then dynamically enabling or disabling those instructions at runtime based on CPU capabilities. But Crypto++ doesn't support that for now.

**Comment by netheril96** [comment]
Basically, by default the `cxxflags` contains `-march=native -mtune=native`. This instructs gcc and clang to build according to the current architecture. You can tune it yourself, such as changing them to `-maes` to enable AES-NI but not other CPU dependent features.

**Comment by Achim16** [comment]
Thanks for the explication, makes perfect sense, I will give the exlained a try
