### ISSUE TITLE
Irremovable Directory Created Upon Mounting

### ISSUE THREAD

**Issue by No0n3Left** [netheril96/securefs#35]
I ran `sudo securefs m ./secfs /Volumes/GMBSDATA`, and this seemed to work. After exiting, the directory /Volumes/GMBSDATA could not be removed with `sudo rm -rf` even. Non-root actions just say `/Volumes/GMBSDATA/: Permission denied` (ls just says `: : Permission denied`), while `sudo rm -rf` says `rm: /Volumes/GMBSDATA/: Device not configured`. Other commands just say `cmdname: /Volumes/GMBSDATA/: Device not configured`. I would try removing it in finder (on a mac), but it does not show up in finder for some odd reason. A full reboot does not remove this directory entry either. Attempting to `sudo cd /Volumes/GMBSDATA` does not show any error and exits clean (exit status=0), but does not actually modify the pwd nor change the directory.

The output of ls -la pertaining to the directory:
`drwx------   1 root   wheel      0 31 Dec  1969 GMBSDATA`

I got the above directory destroyed eventually with diskutil, for some reason it thought it was a device rather than a mount point. After that, I tried again, and mounted it as a directory that I could read and stuff, but I dont know how to unmount it. Killing command doesnt work, only reboot seems to work

--------------------------------------------------------------------------------------------------

I figured out the problem, on Mac OS, you CANNOT try to mount into any subdirectory of /Volumes. I am not sure the exact reason, but it does not seem to be a problem with securefs itself, rather OSXFUSE. Using `sudo` with securefs allowed it to create an access directories within /Volumes, but for some reason does not actually work as expected. See https://github.com/osxfuse/osxfuse/issues/306. According to this, there is a workaround that can be implemented on the FS side (https://github.com/osxfuse/sshfs/issues/27). This would likely be platform specific code, as it is only needed for OSXFUSE, so I am not sure if that would be acceptable or not, but if this is not implemented, I feel a statement should be added to the README about mounting to /Volumes/ not working on Mac OS.

**Comment by netheril96** [comment]
Fixed in 8a6b397f754c5a2ab0d5a6a996931246d958719b.

Don't run `securefs` as root. It will cause all kinds of bizarre problems.
