### ISSUE TITLE
Readme needs updating for macOS

### ISSUE THREAD

**Issue by microbug** [netheril96/securefs#36]
- The name of Apple's operating system is macOS, not OS X (this changed with 10.12)
- You can install osxfuse with homebrew with `brew cask install osxfuse` (instead of using the osxfuse website). This fits better with using brew to install securefs.
- Securefs is no longer in homebrew/fuse (deprecated), the command to install it is now `brew install securefs`.

**Comment by microbug** [comment]
Also, it would be useful to have some more info on format version 1 vs 2 vs 3 vs 4 in the readme.

**Comment by netheril96** [comment]
Updated to reflect your first and second point. I don't like `brew cask`, for it doesn't work well with the packages' builtin update mechanism, so no mentioning of it on README. You are free to install osxfuse with cask if you like, of course.
