### ISSUE TITLE
ver 0.7.3

### ISSUE THREAD

**Issue by JackDinn** [netheril96/securefs#37]
Why am i always getting version 0.7.2 ?

I'v run

```
git clone https://github.com/netheril96/securefs.git
cd securefs
cmake .
sudo make

╭─greg@greg-Inspiron-5767 ~/securefs  ‹master*› 
╰─➤  securefs v
securefs 0.7.2
Crypto++ 5.65
libfuse 29

Hardware features available:
SSE2: true
SSE3: true
SSE4: true
AES-NI: true
CLMUL: true
```

I did have securefs 0.7.2 already installed. I tried "git pull" from within the dir then "cmake/make" and it wouldn't update so i deleted the whole folder and started again but got the result above.

Thank you.

**Comment by netheril96** [comment]
In Linux, when the binary you run is a bare name rather than relative or absolute path, the executable will be looked up in the directories specified by the `PATH` environmental variable. The newly built `securefs` is not in `PATH`. You need to either refer to it by its absolute path, or move and replace the old one.

Run `which securefs` or `type securefs` to see what the shell thinks `securefs` refers to.

**Comment by netheril96** [comment]
Most likely the old one is `/usr/local/bin/securefs`. In that case, `sudo make install` after a successful build should take care of it.

**Comment by JackDinn** [comment]
Yep exactly as you say. There is a lot i need to get my head around i think i need to read up on cmake and make as it looks like i dont understand properly as i thought it would be compiled and installed to the proper path already, but thank you.
```

╭─greg@greg-Inspiron-5767 ~/securefs  ‹master*› 
╰─➤  which securefs
/usr/local/bin/securefs
╭─greg@greg-Inspiron-5767 ~/securefs  ‹master*› 
╰─➤  sudo make install
[sudo] password for greg: 
[ 80%] Built target cryptopp-static
[ 93%] Built target securefs-static
[ 95%] Built target securefs
[100%] Built target securefs_test
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/bin/securefs
╭─greg@greg-Inspiron-5767 ~/securefs  ‹master*› 
╰─➤  securefs v       
securefs 0.7.3
Crypto++ 5.65
libfuse 29

Hardware features available:
SSE2: true
SSE3: true
SSE4: true
AES-NI: true
CLMUL: true

```
