### ISSUE TITLE
Make fails / 0.7.3

### ISSUE THREAD

**Issue by Achim16** [netheril96/securefs#38]
Building of 0.7.3 fails on Debian based LMDE2 whilst 0.7.2 does perfectly.
No issues on Ubuntu 16.04.
Is there any library which needs to be installed in addition ?
Thanks
I enclose the last lines plus attached make output.

/temp/securefs-0.7.3/sources/lite_fs.cpp:475:1: error: expected ‘}’ at end of input
CMakeFiles/securefs-static.dir/build.make:54: recipe for target 'CMakeFiles/securefs-static.dir/sources/lite_fs.cpp.o' failed
make[2]: *** [CMakeFiles/securefs-static.dir/sources/lite_fs.cpp.o] Error 1
CMakeFiles/Makefile2:96: recipe for target 'CMakeFiles/securefs-static.dir/all' failed
make[1]: *** [CMakeFiles/securefs-static.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

[073.txt](https://github.com/netheril96/securefs/files/1103492/073.txt)

**Comment by netheril96** [comment]
What the version of `cmake` on your OS?

**Comment by Achim16** [comment]
It's cmake 3.0.2

**Comment by netheril96** [comment]
Sigh. So apparent CMake 3.0 is not new enough.

Workaround in 9c4f1cb.

**Comment by Achim16** [comment]
Confirm it's working, issue soled. thanks
