### ISSUE TITLE
netiher with gcc nor with clang will it build

### ISSUE THREAD

**Issue by ungentilgarcon** [netheril96/securefs#4]
https://paste.debian.net/440992/

**Comment by ungentilgarcon** [comment]
it is debian jessie 64

**Comment by ungentilgarcon** [comment]
as a temporary measure  I used:   "ln -s /usr/lib/libcryptopp.so.9 libcryptopp.so"

because the file was not there --why?

**Comment by netheril96** [comment]
Checkout the branch `tmp` and try again. If it works, I'll merge it back to `master`.

**Comment by netheril96** [comment]
The change has been merged into `master`. If you build issue persists, please reopen it.

**Comment by netheril96** [comment]
A critical security vulnerability has been found in securefs version 0.4.0 to 0.6.0. If you have used these version to encrypt your data, please either migrate to the newest version or some other encryption software.
