### ISSUE TITLE
option to obfuscate .securefs.json

### ISSUE THREAD

**Issue by bryce-lynch** [netheril96/securefs#40]
I know --config can be used to move the json file elsewhere, but I'd like to use securefs to safely store all my passwords, banking information, documents, etc. on a memory card for emergencies or in case my laptop dies.

However, when an attacker, thief, or other adversary finds the memory card, that .json tells him he's dealing with encrypted data, and gives him some useful information (block_size, etc.)

For this reason I'd like to request some kind of obfuscation (let's says something better than xor...) to be added to the data in the json file.

**Comment by netheril96** [comment]
Security through obfuscation is false security. The only thing you need to concern yourself is the uniqueness, complexity and length of your password.

**Comment by sergeevabc** [comment]
So it is OK to let a third party take possession of ```.securefs.json```?

**Comment by netheril96** [comment]
@sergeevabc 

The only way to attack your filesystem if a third party comes into possession of `.securefs.json` is to try every possible combinations of passwords, barring any security vulnerabilities in my codes. `securefs` also try to delay such attacks by password hashing, which forces the attacker to spend much longer time verifying each password. Any way, if you choose good enough password, third party possession of the file is not a problem. I myself stores it on iCloud, along with my encrypted data.
