### ISSUE TITLE
using securefs via cloud fails because .securefs.json does not exist

### ISSUE THREAD

**Issue by laubblatt** [netheril96/securefs#41]
I am trying to use a securefs to encrypt some of my data on ownCloud / dropbox. 
I created a encrypted directory on my work machine using `securefs create ~/private`, yet when trying to mount it from my home machine I get an error after putting my password:

>  Config file private/.securefs.json does not
> exist. Perhaps you forget to run `create` command first?

What do I have to do to access the encrypted folder on another machine? It looks like that owncloud did not sync the json file.
Any help highly appreciated!

**Comment by netheril96** [comment]
Probably because `owncloud` does not sync files with names start with `.`? You need to consult their documentation to see why `.securefs.json` is not synced.

**Comment by laubblatt** [comment]
Yes you were right.
The owncloud client has an option to sync hidden files which is not active by default. 
After allowing to sync hidden files (note that quite a few other files are now synced) securefs works like a charm! 
Thanks for the great project!
