### ISSUE TITLE
Discrepancy between the file sizes

### ISSUE THREAD

**Issue by sergeevabc** [netheril96/securefs#42]
1. Execute ```securefs create C:\Vault```
2. Execute ```securefs mount C:\Vault Z:```
3. Create ```C:\love.txt``` and put ```Love is all you need``` in. Note its size is 20 bytes. 
4. Copy ```love.txt``` to ```Z:\``` and see how Windows reports its size has become 64 bytes.

Expected: Z:\love.txt must match the size of c:\love.txt, i.e. 20 bytes.

Checksums of both files, however, match, nevertheless it’s quite confusing to the eye.

**Comment by sergeevabc** [comment]
It seems to be the malady of lite format (4), since formats 1, 2,3 has no such visual discrepancy.

**Comment by fxha** [comment]
I tested Windows 10 and there is the same problem.

Seems to be a bug in `LiteDirectoryTraverser` [L329](https://github.com/netheril96/securefs/blob/0.7.3/sources/lite_fs.cpp#L329) on windows. It receives the encrypted file size from storage backend, but on linux there is no problem.

One solution here could be to call `AESGCMCryptStream::calculate_real_size` after we receive the (encrypted) file size (`stbuf->st_size`) on windows.

Maybe @netheril96 can clarify.

**Comment by netheril96** [comment]
Indeed a call to `AESGCMCryptStream::calculate_real_size` is needed here. The bug doesn't show up on Linux and macOS because FUSE API reads only the type field in the `stbuf` buffer during directory traversal. The file sizes are reported by `stat` syscall instead. On Windows, WinFSP has an option I turn on by default to consolidate the calls. In other words, the `stbuf->st_size` is only read on Windows.

A fix is on the way.

**Comment by netheril96** [comment]
Fixed in 324a92fc73d6f2dcb7234e1de3ed4292b09d50d2.

**Comment by sergeevabc** [comment]
Long awaited fix indeed.
I hope an updated binary is on the way as well, since am a mere user without compiler.

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by netheril96** [comment]
New binary released.

**Comment by sergeevabc** [comment]
New binary throws errors while trying to perform basic tasks like creating a new file or folder
```
[Error] [00000000000006E0] [... UTC]    chown path=/New Text Document.txt encounters exception class securefs::VFSException (code=40): Function not implemented
[Error] [00000000000006E0] [2017-11-01 05:33:02.246319900 UTC]    chown path=/November encounters exception class securefs::VFSException (code=40): Function not implemented
```

**Comment by netheril96** [comment]
Does it affect usage?

**Comment by sergeevabc** [comment]
Yes, it does. -_-

**Comment by netheril96** [comment]
I can't reproduce the error locally. Can you provide more information? Which operating system, 32 or 64 bit, what filesystem on, what exactly you do that leads to these errors.

**Comment by sergeevabc** [comment]
Windows 7 x64, NTFS, create new text file and folder via Windows Explorer context menu. 

``` batch
$ securefs073 c c:\Vault4-073
$ securefs073 m c:\Vault4-073 z:
No errors.
```

``` batch
$ securefs080 c c:\Vault4-080
$ securefs080 m c:\Vault4-080 z:
[Error] [00000000000000B0] [2017-11-02 06:27:33.785645400 UTC]    chown path=/love.txt encounters exception class securefs::VFSException (code=40): Function not implemented
[Error] [00000000000000B0] [2017-11-02 06:28:02.392281600 UTC]    chown path=/November encounters exception class securefs::VFSException (code=40): Function not implemented
```

**Comment by netheril96** [comment]
Please mount with option `--trace` and post the log.

**Comment by sergeevabc** [comment]
https://www.pastery.net/gfwhjt/raw/

**Comment by netheril96** [comment]
Hmmm....there is no call to `chown` in my trace log on Windows 10. What is the version of WinFsp on your system?

**Comment by sergeevabc** [comment]
Tried the latest WinFsp 2017.2 B2 and the previous WinFsp 2017.2 B1. Obviously, this is about changes you introduced in 0.8.0, not WinFSP or anything else, as 0.7.3 works fine. Review what was done above the initial request to fix file sizes discrepancy to get to the crux of the matter. And, frankly, I would refrain from developing on Windows 10, since cases of similar failures are not rare.

**Comment by netheril96** [comment]
The two releases are not separated by this single commit. The cause are likely elsewhere. Since I cannot find the root cause, I decide to just silence it, as it is not easy to implement access control on Window right.

Please test this new binary.

[securefs-win.zip](https://github.com/netheril96/securefs/files/1441023/securefs-win.zip)

**Comment by sergeevabc** [comment]
New binary works without aforementioned errors, bravo!

**Comment by sergeevabc** [comment]
By the way, why did you choose to go with scrypt from now on and not argon2 (like Keepass [url=https://keepass.info/help/kb/kdbx_4.html#argon2]did[/url}) or lyra2?

**Comment by netheril96** [comment]
Argon2 is too new so

**Comment by sergeevabc** [comment]
> Since I cannot find the root cause, I decide to just silence it
Does it mean error is still there, but no error message is simply no longer displayed?

**Comment by netheril96** [comment]
The error is caused by `chown` syscall, which is never implemented on Windows. This commit simply turns it  to a no-op if it is ever called.
