### ISSUE TITLE
NTFS symbolic link exception

### ISSUE THREAD

**Issue by fxha** [netheril96/securefs#43]
## Issue

Creating a symbolic link on a NTFS drive gives this error: `getattr path=/link.txt encounters exception securefs::VFSException (code=5): Input/output error`

## System

- OS: Fedora 26
- latest version ([commit 2596467](https://github.com/netheril96/securefs/commit/2596467d63631aab264cf7a63de38fd69b2fda78))

## Steps to reproduce

1. Create a format 4 filesystem on a NTFS drive
2. Mount the filesystem somewhere
3. cd %mount_point%
4. touch empty.txt
5. ln -s empty.txt link.txt (Error)

## How to fix it

I did some initial digging and it looks like [buf->st_size](https://github.com/netheril96/securefs/blob/0.7.3/sources/lite_fs.cpp#L225) is greater than the extracted link size.

**Solution**: Replace `!= buf->st_size` with `<= 0` and resize the string will fix this issue, because we want to determine the link size.

Well, I don't know why the buffer size is greater than the extracted link size.

---
Edit: Created PR #44 for a fix.

**Comment by netheril96** [comment]
Maybe this is related to issue #42 ? Can you test again on the latest commit?

**Comment by fxha** [comment]
No, [324a92f](https://github.com/netheril96/securefs/commit/324a92fc73d6f2dcb7234e1de3ed4292b09d50d2) does not fix the problem. This problem happens when I use Linux (Fedora 26/Ubuntu) and put the encrypted files on a NTFS drive.

**Comment by fxha** [comment]
I opened the link with a hex editor and the symbolic link on the NTFS drive starts with `IntxLNK` followed by the target.

For example:
`IntxLNK.V.B.F.S.N.2.D.U.Z.7.V.8.9.4.6.X.K.Q.N.8.R.K.B.Q.8.C.4.H.T.B.W.8.A.2.`

**Comment by netheril96** [comment]
Why is the issue specific to NTFS?

**Comment by fxha** [comment]
It seem that my NTFS filesystem (created by windows) using [Interix](https://en.wikipedia.org/wiki/Interix) symlinks and UNIX inode's.
