### ISSUE TITLE
Space reservation

### ISSUE THREAD

**Issue by sergeevabc** [netheril96/securefs#46]
Win7 x64, SecureFS 0.8.1, WinFsp 2017.2 B2

Various file managers exist. Some of them (e.g. Windows explorer, [Unreal commander][3], [FAR][5]) reserve space before copying files, others (e.g. [Multi commander][6]) start copying right away. All show excellent performance when dealing with normal disks. Now let’s copy to an encrypted disk. If the file is large enough, there are a huge delay (~1 min for 1.5 GiB file) and a low transfer speed (~10 MiB/s) in the first case, whereas neither delay nor slowdown is noticed in the second case.  

To [illustrate][1] the issue I used [Double commander][2], which Copy dialogue allows to reserve space or not.

Being not a developer, but a mere user, I can only assume the issue is related to a premature attempt to encrypt space being reserved with no actual data in it. Well, you are in a better position to judge.

[1]: https://files.catbox.moe/u4tubp.mp4
[2]: https://doublecmd.sourceforge.io/
[3]: https://x-diesel.com/
[5]: https://farmanager.com/index.php?l=en
[6]: http://multicommander.com/

**Comment by sergeevabc** [comment]
Dear @billziss-gh, this issue may also be of interest for you.

**Comment by sergeevabc** [comment]
- [EncFSMP][1], which depends on [Pismo File Mount][2] driver, seems to be affected by the same issue
- [CPPCryptFS][3] (a Windows port of GoCryptFS), which depends on [Dokany][4] driver, works w/o delays

[1]: https://encfsmp.sourceforge.io/
[2]: http://pismotec.com/pfm/
[3]: https://github.com/bailey27/cppcryptfs
[4]: https://github.com/dokan-dev/dokany/

**Comment by netheril96** [comment]
What is the underlying filesystem? NTFS or FAT32?

**Comment by sergeevabc** [comment]
NTFS

**Comment by billziss-gh** [comment]
@sergeevabc I am on vacation and do not have any means to check things more thoroughly.

@netheril96 is the best person to answer this. However it may be that securefs actually extends files by writing encrypted zeroes in the extended portion of the file. So files end up being written twice. First during a `truncate` call and then during the actual `write`.

**Comment by netheril96** [comment]
The issue results from the lack of sparse files on Windows. `securefs` does not encrypt and write zeros when resizing the file. It writes only two blocks, one at the old end, and one at the new end. But Windows fill the intermediate with zeros, and that is what takes a long time.

I have no idea now how to work around it.

**Comment by sergeevabc** [comment]
Dear @bailey27, could you give a clue on how you worked around space reservation in CPPCryptoFS?

**Comment by sergeevabc** [comment]
@netheril96, also I am confused why you claim there are no sparse files on Windows. Are you [sure][1]?

[1]: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365564%28v=vs.85%29.aspx

**Comment by billziss-gh** [comment]
@netheril96 
> The issue results from the lack of sparse files on Windows. securefs does not encrypt and write zeros when resizing the file.

My understanding of sparse files on NTFS is that they are not enabled by default. One must explicitly enable them with [`FSCTL_SET_SPARSE`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364596(v=vs.85).aspx).

> It writes only two blocks, one at the old end, and one at the new end. But Windows fill the intermediate with zeros, and that is what takes a long time.

You could enable sparseness on NTFS and "punch a hole" using [`FSCTL_SET_ZERO_DATA  `](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364597(v=vs.85).aspx). Given that yours is a portable file system and that NTFS sparse files may have tradeoffs that we do not currently understand, I do not know that I would necessarily recommend this approach.

Is it not possible to somehow eliminate that last encryption block?

----

Many file systems avoid the need to write zeroes upon file extension (`truncate`) by maintaining both a  `filesize` and a `validsize`. The `filesize` maintains the size of the file as seen by user processes. The `validsize` contains the size of valid data within the file. It is always `validsize <= filesize`.

Here is how the `validsize` optimization works. Suppose that at some time it is `validsize==filesize==S`. Then the file system receives a `truncate(T)` with `S < T`. In this case the file system simply updates the `filesize` attribute: `validsize==S < filesize==T`. If it later receives a `read` referencing the range `[S, T)` it notices that the range is beyond `validsize` and simply returns zeroes (`0`) for that range. The `validsize` attribute is only updated when receiving a `write` beyond the existing `validsize`.

**Comment by sergeevabc** [comment]
By the way, [Tixati][1], a cross-platform torrent client, uses sparse method as default for files allocation.

![](http://images.vfl.ru/ii/1510593645/642d6149/19406103.png)

[1]: https://tixati.com/

**Comment by netheril96** [comment]
I added a workaround in the latest commit. I'm not sure if it preserves the semantics on Windows though, especially if it syncs with Unix filesystems via cloud. To be more specific, when I extend the file size with `SetFilePointerEx`, and then read beyond the physical limit, will the data returned be all zeros? If not, then some issues may arise out of this change.

**Comment by billziss-gh** [comment]
@netheril96 
> To be more specific, when I extend the file size with SetFilePointerEx, and then read beyond the physical limit, will the data returned be all zeros? 

Yes, if you use `SetFilePointerEx` to move the file pointer past the end of the file and then do a `SetEndOfFile` or `WriteFile` the file system will guarantee that the range between the previous end of file and the start of the `SetEndOfFile` or `WriteFile` will be zeroes (0). NTFS will do this using the `validsize` trick (when using `SetEndOfFile`) or by filling the "hole" with zeroes (0) (when using `WriteFile` with a non-sparse file) or by possibly recording the "hole" in metadata and possibly filling some parts of it with zeroes (when using `WriteFile` with a sparse file).

In any case a subsequent `ReadFile` in the extended range is guaranteed to return zeroes (0).

**Comment by netheril96** [comment]
Then commit 351cb139969d138ac562df46210464c7d3eeda24 should have fixed it.

**Comment by sergeevabc** [comment]
Ahem, this issue is pretty serious to close it as resolved without verification step, isn’t it? Where’s binary?

**Comment by netheril96** [comment]
Here is the binary.

[securefs-win.zip](https://github.com/netheril96/securefs/files/1480922/securefs-win.zip)
