### ISSUE TITLE
Windows: the "-b" option is no respected when mounting a volume

### ISSUE THREAD

**Issue by mhogomchungu** [netheril96/securefs#47]
As the heading say,when mounting a volume in windows,the process stays on the foreground instead of going to the background.

Example output is below,the output says the process is going to a background but it does not. While on the foreground,the process can be unmounted by sending "ctrl+c" key combo, how is the volume supposed to be unmounted in windows when it finally goes to the background?

```
C:\Qt\5.9.3\mingw53_32>securefs.exe mount -b  -o rw -o fsname=securefs@"C:/vault" -o subtype=securefs "C:/vault" "Z:"
Password:
[Warning] [0000000000000EC8] [2017-11-28 21:58:37.215888200 UTC]    securefs is about to enter background without a log file. You won't be able to inspect what goes wrong. You can remount with option --log instead.
The service securefs has been started.
The service securefs has been stopped.

C:\Qt\5.9.3\mingw53_32>
```

**Comment by netheril96** [comment]
It is actually an issue of WinFSP.

**Comment by mhogomchungu** [comment]
I am working  on SiriKali working on windows to support securefs there but a few things[1] needs to be sorted out first before this becomes a reality.

[1] https://github.com/billziss-gh/winfsp/issues/121

![screenshot 6](https://user-images.githubusercontent.com/3496115/33367029-27fe6b02-d4fe-11e7-95c8-ac42fe807a34.png)

**Comment by billziss-gh** [comment]
I am not familiar with the `-b` option. I am assuming it is a securefs option to daemonize a file system (the `-f` FUSE option or `fuse_daemonize`).

The traditional way of having a long-running background process in UNIX is the daemon. FUSE supports this through `fuse_daemonize` which calls `daemon(3)`. However there is no direct equivalent to the daemon concept in Windows. Therefore what you are trying to do (launch a file system, daemonize it and then control it using a form of an `unmount` command) will not work in Windows.

[For this reason `fuse_daemonize` is a no-op when running WinFsp in native Windows. It actually works and turns the process into a Cygwin daemon when running under Cygwin.]

Windows has the concept of a "service". This concept is closer to the "services" concept under Linux `systemd` or OSX `launchd`. A service needs to be registered with the "Service Manager" (a Windows component). Once registered a service can be started, stopped and interrogated.

WinFsp is Windows software and it therefore embraces Windows architectural principles. This includes support of the Windows Service Architecture for WinFsp file systems. WinFsp supports the following operational modes:

- Command line operation: WinFsp file systems are "console" applications. [Windows differentiates between "console" and "GUI" applications and treats them differently.] This is useful for development and testing from the command line.

- Run as a service: A file system that uses the `FspService*` API's is able to function both as a command line application and a Windows service. This functionality comes for "free" as the file system developer does not need to do anything special. WinFsp-FUSE file systems also inherit this service support for "free".

- Run under the control of the WinFsp.Launcher: For reasons explained in the [Service Architecture](https://github.com/billziss-gh/winfsp/wiki/WinFsp-Service-Architecture) document, WinFsp also includes a launcher (WinFsp.Launcher). The launcher is itself a Windows service and runs file systems in the Windows service context. It has options to list file systems, start and stop them, etc.

How do we reconcile this with SiriKali? IMO the way forward might be that SiriKali (also) performs two functions on Windows:

- Manage the WinFsp.Launcher file system registrations. Such a registration might looks something like:
    ```
    [HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\WinFsp\Services\securefs]
    "Executable"="C:\\...\\securefs.exe"
    "CommandLine"="mount -o rw -o fsname=securefs@%1 -o subtype=securefs %1 %2
    "Security"="D:P(A;;RPWPLC;;;WD)"
    "JobControl"=dword:00000001
    ```

- Communicates with the WinFsp.Launcher by issuing `start`, `stop`, `list` and `info` commands.

We may also have to add some special SiriKali support in the launcher infrastructure.

**Comment by mhogomchungu** [comment]
In Linux and MACOS, a user of SiriKali can:

1. Start SiriKali.
2. Unlock a volume using any one of its backends.
3. Close SiriKali.
4. Start SiriKali again.
5. See a list of unlocked volumes. A user will see unlocked volumes even of volumes that were unlocked independently of SiriKali.
6. Lock a volume that was unlocked at stage 2.
7. Close SiriKali.

Those above steps are possible because:

1. All of its backends can daemonise allowing them to exist independently of SiriKali.
2. All information about list of unlocked volume and their properties can be queried from the system.

In looks like a different approach is needed in windows where:

1. SiriKali will "baby sit" securefs process and processes of future supported backends with a negative effect  of SiriKali being unable to close while a volume is unlocked.

2. With the above, it will also be possible for SiriKali to display all informations about a volume since it obtains them when a volume is being unlocked.

Above two ways are not very elegant(what if SiriKali crashes??) but it seems like its the best way forward with current infrastructure in securefs and winfsp.

**Comment by billziss-gh** [comment]
> In Linux and MACOS, a user of SiriKali can:
> 
> 1. Start SiriKali.
> 2. Unlock a volume using any one of its backends.
> 3. Close SiriKali.
> 4. Start SiriKali again.
> 5. See a list of unlocked volumes. A user will see unlocked volumes even of volumes that were unlocked independently of SiriKali.
> 6. Lock a volume that was unlocked at stage 2.
> 7. Close SiriKali.

This is also possible under WinFsp using the WinFsp.Launcher architecture. See the `launchctl` utility, which allows for command line control of the "launcher".

> SiriKali will "baby sit" securefs process and processes of future supported backends with a negative effect of SiriKali being unable to close while a volume is unlocked.

This really is not necessary. The whole "babysitting" is already done by the WinFsp.Launcher. Please consider reading the [WinFsp Service Architecture](https://github.com/billziss-gh/winfsp/wiki/WinFsp-Service-Architecture) document to understand how this works.

> Above two ways are not very elegant(what if SiriKali crashes??) but it seems like its the best way forward with current infrastructure in securefs and winfsp.

Yes, this approach is not elegant and has quite a few issues. For example, what if the user logs out - do you want the file system to stay alive or not? What if you want the file system to be accessible by multiple users? What if you are running it on a server, which does not run a desktop under normal operation?

You are free to do as you want of course, but IMO it is best to understand the Windows way of doing things rather than trying to shoehorn a UNIX mindset onto Windows.

**Comment by mhogomchungu** [comment]
Lets see what @netheril96 says about using the "WinFsp.Launcher" infrastructure because it will be nice if securefs could do this itself.

**Comment by billziss-gh** [comment]
> Lets see what @netheril96 says about using the "WinFsp.Launcher" infrastructure because it will be nice if securefs could do this itself.

Agree. Although @netheril96 likely does not have to do anything to support the scenario of launching securefs under WinFsp.Launcher. It all can be done by adding a few entries in the registry.

**Comment by mhogomchungu** [comment]
Adding "a few entries in the registry" is a concern for me and i think securefs should be the one to do it. For things to work smoothly in SiriKali, securefs will have to have some sort of an installer that make the registry changes and installs securefs binary in a predictable place and at a place where the registry changes knows about.

**Comment by netheril96** [comment]
Running `securefs` under WinFsp.Launcher will turn it into a service with *admin privileges*, right? That will open a can of worms I am not ready to deal with.

**Comment by mhogomchungu** [comment]
I am closing this one since things seems to be working as upstream expect them to.
