### ISSUE TITLE
Moving the .securefs.json File Post-Creation

### ISSUE THREAD

**Issue by Vesnyx** [netheril96/securefs#48]
Is it possible to move the .securefs.json file after having created a securefs?

Additionally, could the user reference the .securefs.json file from virtually anywhere? Say that I moved to a different computer with my securefs based in the cloud. Would it still be possible to access the directory from the new computer where the .securefs.json is in a different file path?

Issue solved:

Solution is to use command as follows:
`securefs mount --config "PATH to .securefs.json" "data_dir" "mount_path"`

**Comment by netheril96** [comment]
Yes. I don’t remember the option, you can find it with —help

**Comment by mhogomchungu** [comment]
yes, its possible, use "--config" option to specify the path to where the config file is located. The config file can be anywhere your user has read access to.
