### ISSUE TITLE
Encoding Change

### ISSUE THREAD

**Issue by Vesnyx** [netheril96/securefs#49]
So, I saw this commit 351cb13, will be affecting the file encryption by not writing at the end of the file.

1) Is there an ETA on when the next Windows compilation will be released? or at least a guide on how to compile it ourselves since Travis doesn't compile Windows builds. I got a bunch of huge files that have the delay mentioned whenever I try to transfer.

2) Will the encryption change affect already existing files? AKA Will new files be uploaded/written because of this?

**Comment by netheril96** [comment]
Issue #46 prompted the change. The last comment by me has a link to the not yet formally released binary compiled with the fix.

Building it yourself is not hard, if you have CMake and Visual Studio 2015 installed. Just generate the solution with the former and build it with the latter.

The change does not affect existing files.

The next release is at probably the end of this month.

**Comment by netheril96** [comment]
Actually I decide to release 0.8.1 today.
