### ISSUE TITLE
Can't copy any file to the mounted filesystem under OSX

### ISSUE THREAD

**Issue by nodje** [netheril96/securefs#5]
Compilation and execution went fine, however when I try to drag and drop any file to the mounted FS, I get a "not enough free space" error, and I end up with eth zero sized file.
I can create folder without problem though.

**Comment by netheril96** [comment]
Any logs?

**Comment by netheril96** [comment]
Ha, I have the same error as well. I just never did that drag and drop before. I'll investigate.

**Comment by netheril96** [comment]
OK, I have the same error. I just seldom use Finder since it has a lot of unexpected behaviors. I'll try fixing it though.

In the meantime, you can copy and move files with command line, like `cp`, `mv`, or `rsync`.

**Comment by netheril96** [comment]
Fixed in b48c73acbb6c43bffbed8a825bb92ffebafe85df.

**Comment by nodje** [comment]
Great! thanks, working perfectly.
I'm experimenting sharing the encrypted folder with different cloud now.

**Comment by netheril96** [comment]
A critical security vulnerability has been found in securefs version 0.4.0 to 0.6.0. If you have used these version to encrypt your data, please either migrate to the newest version or some other encryption software.
