### ISSUE TITLE
Encryption via keyfile

### ISSUE THREAD

**Issue by theosophist123** [netheril96/securefs#50]
Any chance to have this added somewhen in the future ?

**Comment by netheril96** [comment]
I subscribe to the Unix philosophy. The keyfile is nothing more than a different way of managing password, so it should be external to this program. You can pipe the sha256 of your keyfile into `securefs`.

**Comment by netheril96** [comment]
See previous discussion #28.

**Comment by netheril96** [comment]
Key file is now supported.
