### ISSUE TITLE
Explanation of Meta-File Generation

### ISSUE THREAD

**Issue by Vesnyx** [netheril96/securefs#51]
When storing very large files (> 1 GB), the .meta files tend to be multiple megabytes of storage. When altering the block-size, I can manage to substantially lower the .meta file size at the cost of some transfer speed. I was wondering why such large .meta files are created by this design.

When I was examining the design docs, I noticed [this](https://github.com/netheril96/securefs/blob/master/docs/design.md#encryption-and-authentication) schema for storing the metadata for the file. Other file encryption options like Cryptomator, have substantially less overhead in external file creation, maxing out at a kilobyte. 

The reason I bring this up is because these files make streaming or navigating directories very difficult. In this situation, I am mounting a secureFS volume ontop of Google Drive File Stream's mount. After uploading and clearing the local cache of the encrypted volume, every time I remount, the .meta files are redownloaded. This means that large volumes of large files will result in a massive local cache. I got around this by manipulating the block-size to much higher values, but I am unsure of the security vulnerabilities this may be creating. Is there any way to keep the original 4kb block encryption, but also keep the size of the .meta file reasonably small?

**Comment by netheril96** [comment]
Other crypto filesystems do not defend against the attack of replacement of a certain block with its old revision. The meta file ensures the integrity of the whole file and protects against such attacks. If you are not that paranoid, you can just create securefs format v4, which has substantially lower overhead.

I don't understand your last paragraph. The sizes of the meta file is a fraction of the content file, so if you have to redownload meta files every time, what do you do with the much larger content files?

As for the block size, there is no security implications of enlarging it. The only downside is that even when you request a read/write of very small size, `securefs` still have to read/write and decrypt/encrypt a whole block, so the larger the block size, the more wasted computation.

**Comment by Vesnyx** [comment]
Perhaps it was badly worded. What happens is that Google's File Stream will download the meta file when opening the encrypted files via Windows Explorer, without opening the content. My assumption is that the files necessary for it to populate the file's metadata are present in the .meta file, hence the load. 

In regards to storage, it means that even browsing through the folders with large files will download multiple meta files, even if the content files are never opened. 

In any case, I can see the benefit of this method for encryption and the question has been answered, so I'll close the issue. Thanks!
