### ISSUE TITLE
Folder as mount point (in Windows platform)

### ISSUE THREAD

**Issue by heX16** [netheril96/securefs#52]
OS: Windows 7 x64

Try mount:
```
securefs m D:\Data_Crypt_SFS D:\Data\

[Error] [0000000000003EA4] [2018-01-19 09:52:44.869302300 UTC]    The mount point
must be a drive path, such as Z:
```

But I think it's possible. [encfs4win ](https://github.com/jetwhiz/encfs4win)can do it. (command: "encfs.exe d:\Data_Crypt\ d:\Data\")

**Comment by netheril96** [comment]
This is a deliberate decision. When I last tested it, many applications (or Windows itself) treated the mount point as case insensitive since it is on a NTFS drive.

**Comment by heX16** [comment]
> as case insensitive since 
Does this mean that it is required to specify a path with correct "symbol case"?
Or does this mean that there will be problems with the "symbol case" inside the mount point?

**Comment by netheril96** [comment]
I have not tested it. My understanding is that the mount point, should it be a folder, must be on a case insensitive drive in the first place, or Windows applications will be confused.

**Comment by heX16** [comment]
I found a description of this problem:
https://github.com/billziss-gh/winfsp/issues/36

But is there are no "fundamental" problems.

**Comment by netheril96** [comment]
This one problem is serious enough that I disable it on purpose. I don't know if there are more, since Windows is certainly not fond of the idea of folder mounts.
