### ISSUE TITLE
fatal: cannot update the ref 'HEAD': unable to append to '.git/logs/HEAD': Operation not supported

### ISSUE THREAD

**Issue by CGenie** [netheril96/securefs#58]
Hello,

I have a `git` repository in the encrypted folder. When I try to commit, I get the following error message:

```
fatal: cannot update the ref 'HEAD': unable to append to '.git/logs/HEAD': Operation not supported
```

This comes from the securefs FUSE, from the output in the `mount` command:

```
[Error] [0x7fce15525700] [2018-03-30 06:28:37.980039470 UTC]    open path=/xxx/.git/logs/HEAD encounters exception securefs::VFSException (code=95): Operation not supported
```

I guess some file operation is not implemented? :)

**Comment by netheril96** [comment]
I just tested git operations on my securefs volume and it worked just fine. So the issue is not universal. You need to provide me with more information to replicate the bug, including operating system, underlying filesystem, is either the underlying fs or securefs mounted readonly, etc.

**Comment by CGenie** [comment]
I'm using archlinux and securefs is taken directly from aur:
```
aur/securefs 0.8.1-1 [installed] (3) (0.06)
    A better transparent encryption filesystem
```
I just mount it as: `securefs mount <src> <dst>` without any switches etc.

**Comment by CGenie** [comment]
Hm I created a new git repository and things work fine there, maybe my git repo is broken? But why would it throw a FUSE error?
I copied the whole repo to my ext3 file system, commit works there...

**Comment by netheril96** [comment]
So how do you exactly create such a git repo? You copied it from existing places or you constructed a fresh one on securefs volume?

**Comment by schlomie** [comment]
I can confirm this happens on format 4.

```
$ securefs i priv4
Config file path: priv4/.securefs.json
Filesystem format version: 4
Is full or lite format: lite
Is underlying directory flattened: false
Is multiple mounts allowed: true
Is timestamp stored within the fs: false

Content block size: 4096 bytes
Content IV size: 96 bits
Password derivation algorithm: PBKDF2-HMAC-SHA256
Password derivation iterations: 65536
Per file key generation algorithm: AES
Content cipher: AES-128-GCM
```

But not on format 2.

```
$ securefs i priv2
Config file path: priv2/.securefs.json
Filesystem format version: 2
Is full or lite format: full
Is underlying directory flattened: true
Is multiple mounts allowed: false
Is timestamp stored within the fs: false

Content block size: 4096 bytes
Content IV size: 96 bits
Password derivation algorithm: PBKDF2-HMAC-SHA256
Password derivation iterations: 65536
Per file key generation algorithm: HMAC-SHA256
Content cipher: AES-256-GCM
```


Format 4:

```
[ pseudo ops ]
$ securefs m -b priv4 pub4
$ cd pub4
$ mkdir test
$ cd test
$ git init
$ echo "test" > test.txt
$ git add test.txt
$ git commit -m "added test.txt"
[master (root-commit) baeebe3] added test.txt
 1 file changed, 1 insertion(+)
 create mode 100644 test.txt
$ echo "asdf" >> test.txt
bash: test.txt: Operation not supported  <--- Appending not supported!
$ vim test.txt
$ git commit -a -m "changes"
fatal: cannot update the ref 'HEAD': unable to append to '.git/logs/HEAD': Operation not supported
```

With format 2, all of this is works - I have not tried format 3.


```
[ pseudo ops ]
$ securefs m -b priv2 pub2
$ cd pub2
$ mkdir test
$ cd test
$ git init
$ echo "test" > hello.txt
$ git add hello.txt
$ git commit -m "added hello.txt"
[master (root-commit) 6decce8] added hello.txt
 1 file changed, 1 insertion(+)
 create mode 100644 hello.txt
$ echo "asdf" >> hello.txt
$ git commit -a -m "changes"
[master fbaf6c4] changes
 1 file changed, 1 insertion(+)
```

This happens on any git repo, whether initialized (as seen above) or cloned from another repo, or copied in from some where else, (via rsync, cp -a, or mv)

**Comment by netheril96** [comment]
How do I create a `btrfs` with `compress-force=zlib,noatime`? I cannot reproduce the issue on my current filesystem.

**Comment by schlomie** [comment]
compress-force and noatime are just mount options.

```
# mkfs.btrfs /dev/sdX
# mount -o noatime,compress-force=zlib /dev/sdX /mnt
```

And then from there, proceed to create a format 4 securefs folder.

```
$ cd /mnt
$ mkdir priv pub
$ securefs c priv
$ securefs i priv
Config file path: priv/.securefs.json
Filesystem format version: 4
Is full or lite format: lite
Is underlying directory flattened: false
Is multiple mounts allowed: true
Is timestamp stored within the fs: false

Content block size: 4096 bytes
Content IV size: 96 bits
Password derivation algorithm: PBKDF2-HMAC-SHA256
Password derivation iterations: 65536
Per file key generation algorithm: AES
Content cipher: AES-128-GCM
```

And then you'll see the issue appending to files - doesn't even need to be a git repo, but that's where I think it was first noticed.

```
$ securefs m --log test.log -b priv pub
$ cd pub
$ echo "asdf" > test.txt
$ echo "asdf" >> test.txt
bash: operation not supported: test.txt
```

From the log file:
```
[Info] [0x7ff1804db700] [2018-07-16 14:35:03.671893877 UTC]    init
[Error] [0x7ff17f4d9700] [2018-07-16 14:35:23.976530633 UTC]    open path=/test.txt encounters exception securefs::VFSException (code=95): Operation not supported
```

**Comment by schlomie** [comment]
Interesting ---  So with format 4, it works fine on FreeBSD.   Starting to wonder if it is an issue with the kernel (Ubuntu 4.15.0-24) vs (Arch 4.17.6) or something in the fuse lib.   Interesting though, fuse on Ubuntu 18.04 supplies fuse 2.9.7 -- same as Arch (currently)

Let me spin up an Arch VM and see what happens there.

**Comment by schlomie** [comment]
Ah, I see this, lite_fs.cpp:166/7 - thus the breakage in format 4.
```
        if (flags & O_APPEND)
            throwVFSException(ENOTSUP);
```

So really then, format 2 is broken, against what fuse _should_ be doing?

operations.cpp:335ff, notably 341 and 342.  `O_APPEND` appears to be allowed here?
```
int open(const char* path, struct fuse_file_info* info)
    {
        COMMON_PROLOGUE

        int rdwr = info->flags & O_RDWR;
        int wronly = info->flags & O_WRONLY;
        int append = info->flags & O_APPEND;
        int require_write = wronly | append | rdwr;

        try
        {
            if (require_write && internal::is_readonly(ctx))
                return -EROFS;
            auto fg = internal::open_all(fs, path);
            RegularFile* file = fg->cast_as<RegularFile>();
            if (info->flags & O_TRUNC)
            {
                file->truncate(0);
            }
            info->fh = reinterpret_cast<uintptr_t>(fg.release());

            return 0;
        }
        COMMON_CATCH_BLOCK
    }
```

**Comment by netheril96** [comment]
Format 2 is not broken. It is doing unnecessary work if FUSE keeps its promises, but that additional work does no harm. But now that we see that FUSE can be buggy, maybe I should implement a workaround for format 4 as well.

**Comment by netheril96** [comment]
I pushed a commit 6283c259f8d6a6d269801af2878f954b14958868 working around the FUSE bug to master. Would you try if it solves your problem?

**Comment by schlomie** [comment]
That commit seems to have done it.  Appending now works, and allows git to write to its log file.

**Comment by netheril96** [comment]
Feel free to reopen if the issue shows up again.
