### ISSUE TITLE
Windows: background mode does not work

### ISSUE THREAD

**Issue by smarthouseprojectdotorg** [netheril96/securefs#60]
It looks like adding -b option does not work on Windows 10 and does not run securefs executable in background mode. It simply keeps running when I run it from the command prompt. Tested with a precompiled binary and also compiled it from sources myself. Same result. Is it a known issue or maybe I'm not using it right?

**Comment by netheril96** [comment]
Well, I add some comments in the command line help in commit 3ed2bcb323ef0c9e420d7035f9e4efe478d90ce3.
