### ISSUE TITLE
Alternative Ciphers?

### ISSUE THREAD

**Issue by schlomie** [netheril96/securefs#63]
Curiosity - any goals or desire to abstract the crypto to support alternate ciphers, notably Twofish?

**Comment by netheril96** [comment]
Twofish is not more secure than AES, and definitely slower on most platforms.

**Comment by schlomie** [comment]
Agreed on both - AES-NI is blazing.  This wasn't a really a feature request, or project plan, just strictly curiosity.

Thanks!

**Comment by netheril96** [comment]
I originally intended to implement both AES-GCM and CHACHA20-Poly1305, but the latter was not implemented in Crypto++. Now I don't have the time or the motivation to allow different ciphers.

**Comment by schlomie** [comment]
Well, this is a great project either way.  I only asked about Twofish because I'm a fan of Bruce Schneier and I find Feistel networks fascinating.
