### ISSUE TITLE
Obfuscate modification times

### ISSUE THREAD

**Issue by jpdoyle** [netheril96/securefs#65]
This might not be an issue, as I haven't tried all the different formats yet -- do any of the current formats allow the timestamps of files in `securefs` to be set separately from the encrypted files themselves? If not, this is a data leak.

It's not the same issue as having *modification times* preserved -- as the documentation points out, this is stored in the filesystem anyway (unless you `touch` all the encrypted files in random order occasionally, which is a perfectly valid obfuscation approach). However, an archived folder might have many timestamps that are different from the local machine's modification time, and could be a serious information leak. For instance, I have a large archive of files copied via `rsync` (which preserves timestamps), and even though the file structure is currently encrypted, a clever adversary could get a lot of information by assuming that files with similar timestamps are all in the same folder.

**Comment by netheril96** [comment]
`securefs create --format 3`
