### ISSUE TITLE
Bug: VFSException code 40 on mount

### ISSUE THREAD

**Issue by illusoryOne** [netheril96/securefs#67]
```
.\securefs.exe mount Z:\confidential\securefs V:
[Info] [0000000000002538] [2018-07-08 04:00:42.712450700 UTC]    init
[Error] [0000000000002538] [2018-07-08 04:00:42.714373800 UTC]    readlink path=/ encounters exception class securefs::VFSException (code=40): Function not implemented
The service securefs has been started.
```
Additional info:
- Windows 10 Home Version 1803
- securefs 0.8.2
- Winfsp Version 1.3 (2018.1)

If there's any additional info you could use to help resolve the issue, let me know--I'm completely new to opening issues on Github. Thank you for this great piece of software :)

**Comment by netheril96** [comment]
Windows has very limited support for symbolic links, and few programs make use of it anyway, so I do not bother to implement it. What program initiated the `readlink` call?

**Comment by illusoryOne** [comment]
How can I properly check which program initiated the `readlink` call? I wouldn't be surprised if StableBit Drivepool is the culprit to this issue, so I'll try moving all the files to a single drive in the meantime & get back to you if this resolves the issue. As a side note, I checked my pooled drives individually & the pool mount letter for symlinks using `dir /AL /S $nameOfDrive:\`, but it reported that no symlinks exist.

**Comment by illusoryOne** [comment]
Moved all the files to one drive. Issue still persists, unfortunately. 

No programs are giving any indication of symlink creation errors as expected (because I have no symlinks). Very odd. No worries about implementing the feature unless others are experiencing similar issues. I might try making a new vault, transfer some test data into it, and see if I still get the issue.

**Comment by illusoryOne** [comment]
Update: I re-downloaded/installed Winfsp, the VC++ redistributable, & securefs to make sure my executables weren't corrupt & the installations had went okay. I finally managed to silence the thrown error messages in securefs by using WinFsp 2017.2 instead of WinFsp 2018.1. I know WinFsp 2018.1 brought a **ton** of new changes, so I'm almost certain that broke something in your existing codebase. Hope this helps!

**Comment by netheril96** [comment]
It is not your mistake. I did not anticipate WinFsp may have backwards incompatibility. Next time I will make it clear what WinFsp version `securefs` has been tested against.

**Comment by cw789** [comment]
Even if this issue is closed for now.
Just to note down this error is still happening with WinFsp 1.4 (2019.1).
But with using lite mode it seems to not do any harms - securefs is still working as expected.

**Comment by netheril96** [comment]
I'll put a new binary compiled against the latest WinFsp lately. Let's see if the issue is truly resolved this time.

**Comment by netheril96** [comment]
Try https://github.com/netheril96/securefs/releases/tag/0.8.3

**Comment by cw789** [comment]
No the new release doesn't resolve this error.

**Comment by netheril96** [comment]
60eb3cc9b2aa9ca84795d1b9ffffd6826d9f82dd should fix it. Basically just disabling symlink related functions from the beginning.
