### ISSUE TITLE
Cannot chown on mount path

### ISSUE THREAD

**Issue by Yanhao** [netheril96/securefs#68]
After mount a securefs filesystem on some mount path by root. I found that I cannot use chown or chgrp to change the file permission of the mount path. Is this a bug or intentional？ If it is intentional, What I need to do to make the path mounted by root  accessible by some ordinary user?

**Comment by Yanhao** [comment]
Thanks for replying, But I tried using setuid and seteuid before mount the filesystem to change the user from root to a normal user, and this cause neither root nor the normal user can access  the filesystem. I got very confused. Could you give some advice? thanks in advance.

**Comment by netheril96** [comment]
Try mounting with `-o allow_other -o default_permissions`. The meaning of these flags and other possible flags can be seen on [FUSE manpage](http://manpages.ubuntu.com/manpages/trusty/man8/mount.fuse.8.html).

Warning: I have never tested such configuration. It may screw up your data.

**Comment by Yanhao** [comment]
Fix the problem by setgid before setuid :sweat_smile:

**Comment by Yanhao** [comment]
I see , thanks for the info.
