### ISSUE TITLE
question

### ISSUE THREAD

**Issue by gggin** [netheril96/securefs#7]
can this use in windows?

**Comment by netheril96** [comment]
Sorry, Windows support requires too many changes. And I seldom use Windows so I am hardly motivated.

**Comment by netheril96** [comment]
Experimental support for Windows is added. Checkout the branch `win`.

**Comment by gggin** [comment]
Thank you very much!

**Comment by netheril96** [comment]
A critical security vulnerability has been found in securefs version 0.4.0 to 0.6.0. If you have used these version to encrypt your data, please either migrate to the newest version or some other encryption software.
