### ISSUE TITLE
Cannot override FUSE uid/gid on Windows

### ISSUE THREAD

**Issue by fincs** [netheril96/securefs#70]
On Windows, [a hardcoded uid/gid setting is added after the custom FUSE options provided by the user](https://github.com/netheril96/securefs/blob/master/sources/commands.cpp#L883), therefore taking precedence. It is necessary for me to provide a custom gid to work around a weird user group issue in my system (see https://github.com/billziss-gh/winfsp/issues/204)

**Comment by netheril96** [comment]
b6eb601bdeebe787829828d124ef7fce2b66b28d should fix it.

**Comment by netheril96** [comment]
Feel free to reopen if it doesn't actually fix the issue.
