### ISSUE TITLE
Small Mac-Integration

### ISSUE THREAD

**Issue by warmup72** [netheril96/securefs#75]
Hi,
searching a crypt-Tool with Mac-Integration.
Unfortunally securefs is not full integrated:
- Folder-Icons: Doesn´t work - They aren´t shown
- Tags: If I copy a tagged-File the tag is gone. If I set a new tag i get Finder Error 43
- Spotlight: The files aren´t in the Spotlight

Is there a plan to integrate this functions?
Thx

**Comment by netheril96** [comment]
> Spotlight: The files aren´t in the Spotlight

That is a limitation of `osxfuse`. The mounted filesystem is treated as remote, so Spotlight won't index it. More importantly, though, it does not make sense for Spotlight to index encrypted contents. Spotlight keep index in plaintext, so it would defeat the purpose of encryption entirely were Spotlight indexing `securefs`.

As for the other issues, I need to investigate further. There are scant resources about how they are implemented under the hood, so it may not be an easy task.

**Comment by warmup72** [comment]
Thank You for the answer. Other Encrypter like gocryptfs or cryptomator have a spotlight-integration. I thought they also use fuse?

**Comment by netheril96** [comment]
I don't know how they implement that, but as I have said, it would defeat
the purpose of encryption.

**Comment by netheril96** [comment]
The problem with tags is that they are stored in extended attribute `com.apple.FinderInfo`. But apple stupidly hardcodes the size of this xattr, so it cannot be encrypted, as encryption changes the length.
Therefore I completely [disable the usage of this xattr](https://github.com/netheril96/securefs/blob/master/sources/lite_operations.cpp#L514).

**Comment by netheril96** [comment]
It could be worked around though, if you truly think it is very important for you to have tags. Just need some time to implement.

**Comment by netheril96** [comment]
To have spotlight index the contents, you may try mounting with `-o local`. It may lead to bugs though.

**Comment by warmup72** [comment]
Thx for the answer - I will try the mount-option and will tell the result.
Unforunally I defintiv need the tags. I´ve implemented EASYFILER for my DMS and this software will need tags.

**Comment by netheril96** [comment]
OK, I'll implement tags support in the following week.

**Comment by warmup72** [comment]
I´ve tried mounting

securefs m -o local ./cry/ ./data/

but unforunally the files aren´t shown during the spotlight search

**Comment by netheril96** [comment]
Fixed at master.

**Comment by netheril96** [comment]
Tags are fixed. Others are pending.

**Comment by warmup72** [comment]
Fine I will give it a try!
It would be great to have the full Mac-Integration. 
It seems that apart of Boxcryptor no other Encrytion-Tools has the full integration

**Comment by netheril96** [comment]
Can you try mounting with `-o local -o allow_other`? According to [this](https://github.com/osxfuse/osxfuse/wiki/Mount-options), `allow_other` is the flag needed for Spotlight.

**Comment by warmup72** [comment]
I´ve tried to use Tags with 0.11.1 but they don't work.
Copie a file to securefs. Set a Tag. Close the File-Info and reopen it - Tag is gone.

**Comment by netheril96** [comment]
> I´ve tried to use Tags with 0.11.1 but they don't work.
> Copie a file to securefs. Set a Tag. Close the File-Info and reopen it - Tag is gone.

It worked on my mac at the latest commit. Can you try again?

**Comment by warmup72** [comment]
Hi,
I can not install securefs on my macOS 12.3.1

brew install securefs
Error: securefs has been disabled because it requires closed-source macFUSE!

**Comment by warmup72** [comment]
Hi, I can confirm, that some tags work.
If You add the existing color tags like blue, yellow, etc. they work.
If You create your own tags they don´t work.

**Comment by netheril96** [comment]
I wasn’t familiar with that. How do you create a custom tag?

**Comment by warmup72** [comment]
It´s quite simpel.
> Open Finder
> Open Information of a file (CMD-I)
> Belove the Filename You will find the Tag-Field. There You can type an tagname and hit Enter

**Comment by netheril96** [comment]
Fixed in commit 1b9670dc87fe3089e5bad1c9c2fde6c6b99dad5e

You can remove the previous version `brew rm securefs-mac` and reinstall from my forked repo

`brew install --HEAD netheril96/fuse/securefs` to try it.
