### ISSUE TITLE
Compiling fails at Ubuntu 18.04.2

### ISSUE THREAD

**Issue by stayen** [netheril96/securefs#77]
When trying to build on Ubuntu 18.04.2: the prerequisites (fuse dev files) are installed, and from the directory where the master has been cloned:

    # mkdir build
    # cd build
    # cmake ..
    # cmake ..
    -- The C compiler identification is GNU 7.4.0
    -- The CXX compiler identification is GNU 7.4.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- *************************************************************************
    The Crypto++ library does not officially support CMake. CMake support is a
    community effort, and the library works with the folks using CMake to help
    improve it. If you find an issue then please fix it or report it at
    https://github.com/noloader/cryptopp-cmake.
    -- *************************************************************************
    CMake Error at external/cryptopp/CMakeLists.txt:273 (string):
      string sub-command FIND: unknown last parameter
    
    -- Performing Test CRYPTOPP_IA32_SSE2
    -- Performing Test CRYPTOPP_IA32_SSE2 - Success
    -- Performing Test CRYPTOPP_IA32_SSSE3
    -- Performing Test CRYPTOPP_IA32_SSSE3 - Success
    -- Performing Test CRYPTOPP_IA32_SSE41
    -- Performing Test CRYPTOPP_IA32_SSE41 - Success
    -- Performing Test CRYPTOPP_IA32_SSE42
    -- Performing Test CRYPTOPP_IA32_SSE42 - Success
    -- Performing Test CRYPTOPP_IA32_CLMUL
    -- Performing Test CRYPTOPP_IA32_CLMUL - Success
    -- Performing Test CRYPTOPP_IA32_AES
    -- Performing Test CRYPTOPP_IA32_AES - Success
    -- Performing Test CRYPTOPP_IA32_SHA
    -- Performing Test CRYPTOPP_IA32_SHA - Success
    -- Performing Test CRYPTOPP_IA32_NATIVE
    -- Performing Test CRYPTOPP_IA32_NATIVE - Success
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - not found
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE  
    -- Platform: x86_64
    -- Native arch: FALSE
    -- Compiler: /usr/bin/c++
    -- Flags: 
    -- Build type: Release
    -- Performing Test HAS_THREAD_LOCAL
    -- Performing Test HAS_THREAD_LOCAL - Success
    -- Performing Test HAS_CLOCK_GETTIME
    -- Performing Test HAS_CLOCK_GETTIME - Success
    -- Performing Test HAS_FUTIMENS
    -- Performing Test HAS_FUTIMENS - Success
    -- Performing Test HAS_UTIMENSAT
    -- Performing Test HAS_UTIMENSAT - Success
    -- Configuring incomplete, errors occurred!
    See also "/home/user/install/securefs/build/CMakeFiles/CMakeOutput.log".
    See also "/home/user/install/securefs/build/CMakeFiles/CMakeError.log".

No makefiles are created. What's being done wrong?

**Comment by netheril96** [comment]
It is a cmake error. I don't really know what is the problem, because both older and newer cmake works just fine. Have you modified your cmake installation?

**Comment by stayen** [comment]
@netheril96 Negative, I didn't modify it - directly from repository (package version 3.10.2-1ubuntu2).

Shall I provide any additional info?

**Comment by netheril96** [comment]
That `CMakeLists.txt` file is directly from https://github.com/noloader/cryptopp-cmake. Can you try following its instructions and build the latest Crypto++ with the latest `CMakeLists.txt`? If that works, I'll update the embedded Crypto++. If that doesn't, you may report the issue to that repo instead.

**Comment by netheril96** [comment]
The Crypto++ embedded has been updated. Could you try building again?

**Comment by stayen** [comment]
> The Crypto++ embedded has been updated. Could you try building again?

cmake step ran without errors. Subsequent 'make' produced some warnings, but both securefs and securefs_test executables have been build.

Thanks!

**Comment by netheril96** [comment]
Glad to here it works now.
