### ISSUE TITLE
Windows: copy file to the mounted drive. The filename, directory name, or volume label syntax is incorrect

### ISSUE THREAD

**Issue by 174n** [netheril96/securefs#78]
> [Error] [0000000000002324] [2019-07-31 16:03:34.407134900 UTC]    create path=/phone/books/�������������� ������/1. �������������� ������ ���������� ������������������ (DISCWORLD) - ���� ���������������� �� ����. ���� (�������������������� �������������� ��������).mp3 encounters exception class securefs::WindowsException (code=2): error 123 The filename, directory name, or volume label syntax is incorrect. (CreateFileW(path=\\?\G:\securefs\encrypted\FTPT8NNSBN36NHDE8N9WPFSEPW4V5E269N\3R2D4YU89WQFX4N8GVSMCNABQ9U6XGY2AW\FAK6KD873DT8D6SGX539U4H427IGJDGYFFA5AEHNGSUJXUQKI89QQZK4I7CS\6SANXBH9XKS9JBX86H7CG9VVG7ZHFWGPHTGUE59TCXSUFBQ3MRUASZSWPTJ3VZNJN4ZSU6QAJN3HXKG3SIBE8FDDUAXS2MGIUJ9Z6U8NQEJ78MUHXXEZNUPU94UBDR7W3532BQRVMIB5NIYJPV545SUFM9HXFW6Q6JRU656Q3SR987Q2JSGI5FAYFR8BGPI8E4NV4WTJVUDG3WR4KJ2FNZZK48G6PWYTVM4W38K4SNQN4YXK4NAGMPX4RNGENYGGXYKMHN26G7V63JDUXN))

**Comment by Rundik** [comment]
I think I need to use shorter hashing algorithm for the file names, but I didn't found how to change this

**Comment by netheril96** [comment]
It seems a bug in `securefs`. The actual path created should start with `\\?\G:\securefs\encrypted`, not a single `\`. But I can't tell from your log how it happened. Do you have the actual original path? The �� are probably not the original characters.

**Comment by netheril96** [comment]
The filename component is too long in this case.
