### ISSUE TITLE
Port to Windows

### ISSUE THREAD

**Issue by neuhaus** [netheril96/securefs#8]
Compared to EncFS, securefs has advantages. However, it's only available on Linux and OS X right now.

Feature request: Port to Windows

**Comment by netheril96** [comment]
> On Debian based Linux distro, you need to install fuse and libfuse-dev. On RPM based Linux, you need fuse and fuse-devel. On OS X, you need osxfuse. Operating systems other than OS X and Linux are not supported for now.

The README has stated crystal clear that OS X is supported. In fact, I do my development on OS X, use `securefs` on OS X, and only test very infrequently on Linux in a VM.

**Comment by neuhaus** [comment]
Yes, I noticed that and had changed my issue already by the time you replied :-)

**Comment by netheril96** [comment]
I'm thinking about a Windows port, but have no concrete time plan about when it will be implemented. It is a significant undertaking as I have to massage the build system, rip apart all the system calls, and deals with the dreaded Code Page problem.

The first step is to separate the OS independent part from the dependent part.

**Comment by netheril96** [comment]
Experimental support for Windows is added. Checkout the branch `win`.

**Comment by neuhaus** [comment]
Thanks!

**Comment by netheril96** [comment]
A critical security vulnerability has been found in securefs version 0.4.0 to 0.6.0. If you have used these version to encrypt your data, please either migrate to the newest version or some other encryption software.

**Comment by sergeevabc** [comment]
Would be great to extend Windows section of readme for new users.
You see, path notation ```~/Secret``` and mount point ```~/Mount``` are not common here.

**Comment by netheril96** [comment]
@sergeevabc Open a new issue.

**Comment by mhogomchungu** [comment]
SiriKali[1] now has a windows port making it possible to use securefs with a GUI tool.

[1] https://mhogomchungu.github.io/sirikali/
