### ISSUE TITLE
Windows: console error on copying\moving files into mountdir from any source (but works fine)

### ISSUE THREAD

**Issue by Owyn** [netheril96/securefs#81]
when I copy and paste file inside mountdir or cut & paste aka "move" (original file is inside mountdir too) (even into different folder) console gives red errors, is this normal? (but files copy fine I guess)

```
[Error] [00000000000011F4] [2019-09-11 17:41:11.300788400 UTC]    create path=/Test.txt encounters exception class securefs::WindowsException (code=17): error 80 File already exists. (CreateFileW(path=\\?\V:\SF\N3393I5PPC8TQIC2KEBMYFMKI2DN4QVUF6CKH4I))
[Error] [00000000000011F4] [2019-09-11 17:42:11.625519100 UTC]    mkdir path=/Test_Folder encounters exception class securefs::WindowsException (code=17): error 183 Can not create file because it already exists. (CreateDirectory(path=\\?\V:\SF\5FB2C5RUYS2BZZMWEMTIHAHBM4ZG662IBAUJY4PXZTWA))
```
Windows 10 b1903
SFS 0.8.3
WinFsp 2019.3 B2

**Comment by netheril96** [comment]
Did you make these operations on the command line or from Windows Explorer?

**Comment by Owyn** [comment]
Windows explorer

**Comment by Owyn** [comment]
after updating to latest secureFS version error `error 80 File already exists.`  is gone, but first one `error 183 Can not create file` is still there in the verbose console output for folders I move\copy stuff into (from the same mounted drive or from another local drive)
```
[Error] [00000000000011F4] [2019-09-11 17:42:11.625519100 UTC]    mkdir path=/Test_Folder encounters exception class securefs::WindowsException (code=17): error 183 Can not create file because it already exists. (CreateDirectory(path=\\?\V:\SF\5FB2C5RUYS2BZZMWEMTIHAHBM4ZG662IBAUJY4PXZTWA))

```

**Comment by netheril96** [comment]
I don't know what is the root cause. Perhaps Windows Explorer tried creating the file twice?

**Comment by Owyn** [comment]
> mkdir 
I think explorer is trying to create the **folder** user moves\copies things into each operation, but that's a bit weird for explorer to do, can't it be secureFS\WinFSP?

**Comment by Owyn** [comment]
Weird thing, if I drag an image from Firefox browser to the folder - there is no error, but If I right click the image in the browser and use "save image as" to that folder I get create path error 80:

```
[Error] [0000000000000544] [2019-10-01 17:36:58.791749400 UTC] [int __cdecl securefs::lite::create(const char *,unsigned int,struct fuse_file_info *):222]    create path=/Test_Folder/image_from_internet.jpg encounters exception class securefs::WindowsException (code=17): error 80 Файл существует. (error 80 file exists) (CreateFileW(path=\\?\V:\UP\SF\5FB2C5RUYS2BZZMWEMTIHAHBM4ZG662IBAUJY4PXZTWA))
```

**Comment by netheril96** [comment]
If you can't observe anything wrong, then the error message is superfluous. It is not uncommon for applications to create a directory just in case, and ignore `EEXIST` errors.
