### ISSUE TITLE
Request: Signed releases

### ISSUE THREAD

**Issue by holgersson32644** [netheril96/securefs#85]
Hi,
can you please sign future releases, so trusting the code wouldn't be
a question of trusting github.com anymore?

Best regards,
Nils

**Comment by netheril96** [comment]
But how do you obtain my PGP key? From GitHub? In that case, you still have to trust GitHub.

**Comment by holgersson32644** [comment]
There are plenty ways:
- *once* published via github.com, or
- via your mail provider and WKD (web key directory), or
- via keybase.io, or
- via the "new" gpg servers based on the software hagrid, which check if you can access the email address you use as a key UID.
This is just a list of spontaneus ideas, and as stated in the first one, one has to trust github.com at most once, but not forever which is not perfect, but increases security partially.

**Comment by netheril96** [comment]
I've registered a keybase account, which is a interesting platform. I've signed the latest commits, tags and binary releases. Thanks for the suggestion.
