### ISSUE TITLE
Compiling under Debian 10 Buster

### ISSUE THREAD

**Issue by m23project** [netheril96/securefs#86]
Hi,

here are the compile instructions for Debian 10

Install the needed libutf8proc library:

```
apt install libutf8proc-dev
```

Make sure, the incude file is available where securefs's .cpp/.h are expecting it to be:

```
mkdir /usr/include/utf8proc
ln -s /usr/include/utf8proc.h /usr/include/utf8proc
```
Now (and not before) call cmake in the securefs source directory:

```
export LDFLAGS='-lutf8proc -L/usr/lib/x86_64-linux-gnu'; cmake .
```

Compile with:

```
make
```

**Comment by netheril96** [comment]
I've updated the instructions. The code base has embedded utf8proc, but it needs to be fetched by `git submodule` calls.
