### ISSUE TITLE
Add ability to set path for .securefs.json

### ISSUE THREAD

**Issue by Sonnix1** [netheril96/securefs#9]
Currently settings and encryption key is stored in .securefs.json which is located in the folder with all the encrypted data.
Would it be possible to add an option to specify the path for the settings file so that it could be stored on some external media separate from encrypted data or in separate folder that is not synced with the cloud?
In this setup the mount command for example could look like:
securefs mount --config /mnt/external/.securefs.json ~/Secret ~/Mount

**Comment by netheril96** [comment]
What is the use case for this?

**Comment by netheril96** [comment]
Mm, I get it. If you do not store `.securefs.json` in the cloud along with your data, you deny the attacker any chance to guess or brute force your password. They will have to brute force the 256-bit random key instead. I will implement it soon.

**Comment by netheril96** [comment]
Added in 73474dc2061161b52212cfe49c904d1f92a8714e.

**Comment by netheril96** [comment]
A critical security vulnerability has been found in securefs version 0.4.0 to 0.6.0. If you have used these version to encrypt your data, please either migrate to the newest version or some other encryption software.
