### ISSUE TITLE
Securefs Invalid Password [int securefs::commands_main(int, const char* const*):1262]

### ISSUE THREAD

**Issue by dhammel** [netheril96/securefs#90]
I am running Kubuntu 19.10, fully updated.

I noticed this issue during upgrade from 0.8.3 to 0.9.0
Issue persist in 0.9.0

I went to mount folder and returned this error: [Error] [0x7fd3c0ae5080] [2020-01-06 19:07:33.281951802 UTC] [int securefs::commands_main(int, const char* const*):1262]    Invalid password

It is not an incorrect password. I managed to mount the folder by downgrading back to 0.8.3. Which worked only after a restart.

After being able to mount it, and knowing it wasn't corrupted data I then updated back to 0.9.0 and I was able to mount it but then I closed it, re-mounted it and got this error again. Not sure exactly whats going on with it, but I know based on the troubleshooting i've been able to do myself that its not corrupted data or incorrect password. I don't know if its something conflicting on my computer or a bug in the new version. I haven't been able to reproduce this issue on version 0.8.3

securefs v command outputs: 
securefs 0.9.0-4-ge87d5eb
Crypto++ 8.2
libfuse 29
utf8proc 2.4.0

Hardware features available:
SSE2: true
SSE3: true
SSE4.1: true
SSE4.2: true
AES-NI: true
CLMUL: true
SHA: false

**Comment by netheril96** [comment]
What is the output of `securefs info’`

**Comment by netheril96** [comment]
The version is weird. `0.9.0-4-ge87d5eb` means it is not on the 0.9.0 release, but 4 commits after it. However, `ge87d5eb` is not a commit in this repo. Did you make local modifications?

**Comment by dhammel** [comment]
securefs info output:
Config file path: dhammel.securefs/.securefs.json
Filesystem format version: 2
Is full or lite format: full
Is underlying directory flattened: true
Is multiple mounts allowed: false
Is timestamp stored within the fs: false

Content block size: 4096 bytes
Content IV size: 96 bits
Password derivation algorithm: scrypt
Password derivation iterations: 4194304
Per file key generation algorithm: HMAC-SHA256
Content cipher: AES-256-GCM

at the current time, it seems to mount/unmount fine but I can't hold up the luck it may start acting funny later. As for the version, I did not make any local modifications that I am aware of.

Last version I installed was 0.8.3, I downloaded the .tar.gz archive from the releases sections for this version.

For 0.9.0 it said not to download source from releases, to use --recursive when clone which is what I did. In cli I ran: git clone --recursive https://github.com/netheril96/securefs.git
I cd into it, and ran: cmake CMakeLists.txt && make && sudo make install which in this case overwrote 0.8.3. When running the securefs v, that is what was outputted.

**Comment by dhammel** [comment]
I am closing this issue, as I have determined that there was an issue with my ram as I started having other symptoms not related to securefs, after finding out this, I ordered new ram & once I installed it, I haven't been getting this issue anymore.
