### ISSUE TITLE
Add flock-free mode

### ISSUE THREAD

**Issue by divVerent** [netheril96/securefs#91]
I am using securefs on an underlying file system that does not support flock(), namely Chrome OS's Linux container when accessing an USB drive.

As securefs in format 2 (my preferred mode as it hides the directory structure) is single threaded anyway, there is no real need for any locking unless you fear another concurrent mount of the same securefs.

I am currently actually using securefs just fine there with a LD_PRELOAD library that grounds flock() and adds special handling for open() with O_RDONLY | O_CREAT which it also does not support (that's clearly their bug though).

Now I do know that Google should rather just fix their stuff in Chrome OS. But not only will that take a while, having an option to remove these locking calls can also be a large performance advantage when running on top of file systems that implement flock() slowly (e.g. NFS), provided of course that concurrent mounts are prevented another way (technically the .securefs.lock file should be achieving that already anyway).

**Comment by netheril96** [comment]
I don't quite remember how I implemented format 2. But searching lock
<https://github.com/netheril96/securefs/search?p=1&q=lock&unscoped_q=lock>
seems
to indicate the flock is never called in format 2.

**Comment by divVerent** [comment]
Good, this is good news. Looks like indeed there are only few call sites.

```
[divverent@penguin usb]$ nolok.c securefs mount -s .sec sec
nolok initialized.
Password: 
nolok: rewriting open mode for .securefs.lock.
```

Then reading or writing files in there does not trigger a flock().

```
[divverent@penguin usb]$ nolok.c securefs fix  .sec 
nolok initialized.
Password: 
nolok: skipping flock("/mnt/chromeos/removable/USB Drive/.sec", 6).
```

There's a flock() that could be easily made optional.

**Comment by netheril96** [comment]
Fixed at head
