### ISSUE TITLE
wishlist: consider replace python2 with python3

### ISSUE THREAD

**Issue by Yanhao** [netheril96/securefs#92]
The python2 is officially EOF since 2020, so it is time to obsolete python2. 
The changes is trivial, just replace *xrange* with *range* within test script simple_test.py, and change the Shebang to #!/usr/bin/python3.

**Comment by netheril96** [comment]
Can you file a pull request?

**Comment by netheril96** [comment]
Fixed in ce1fed6ac8e83301b093d46e5742902bbc037465
