### ISSUE TITLE
editing any file hangs while it used to work (windows) - fine in linux

### ISSUE THREAD

**Issue by shuther** [netheril96/securefs#93]
Windows explorer hangs when I try to create a new file, move files, ... within the securefs folder.
It used to work fine; it seems linked to my migration to freenas 11.3 (new way to handle the permissions/ACL with samba) but it is working fine under linux so not really sure if it is the problem?

It is still working fine if I do it using linux/ubuntu (i.e. nautilus to move folder, touch ...).

Tested on: latest windows 10, Winfsp, securefs
cmd.exe hangs also if I move to the securefs disk (m:); I have to kill securefs to get a prompt again.

no error without trace enabled.

Hope it helps
[trace.log](https://github.com/netheril96/securefs/files/4193577/trace.log)

**Comment by shuther** [comment]
I guess there is no link, but on linux, the trace starts by:
...Opening file on a NTFS volume.
I mount a storage using SAMBA from freebsd/ZFS; so it is definitely not a NTFS volume.

Maybe it is just related a windows lib you are using; the message could be confusing on a linux box.

**Comment by netheril96** [comment]
On Windows `securefs` is hardcoded to work only on NTFS. Perhaps that is why it hangs, since in your case the underlying volume is a network filesystem.

**Comment by shuther** [comment]
Using ProcessXP in windows is showing that any process touching a file (likely requesting write access) within securefs (like word, ...) gets a status: Suspended; not sure if that helps.

**Comment by netheril96** [comment]
Can you try securefs on a NTFS volume? If it works on NTFS then I know where I should look for the root cause.

**Comment by shuther** [comment]
so it does work on a NTFS volume; it does not work any more when I mount the shared drive (it used to work, so I am not sure if the issue is connected with the latest SAMBA/freenas/permissions); I also tried to create a new securefs volume (on samba); it starts to hang when I create a new file (explore hangs); I had 2 files in the crypted folder (secure.json and the a crypted name with a size of 0); so it looks ok on this side?

**Comment by shuther** [comment]
When I copy a file into the securefs enclave, I noticed that the file is created but the size is 0. anything I can do so we can debug it?

**Comment by netheril96** [comment]
Try [this branch](https://github.com/netheril96/securefs/tree/all-ntfs) that treats all volumes as NTFS. DO NOT try with your critical data.

**Comment by shuther** [comment]
is there a windows release for it by chance?

**Comment by netheril96** [comment]
Here it is x64 version.

[securefs.zip](https://github.com/netheril96/securefs/files/4288250/securefs.zip)

**Comment by shuther** [comment]
I had no luck to execute the program, I am ending up with error 0xC0000.22 as per attached (windows error)
![Screenshot 2020-03-08 at 09 39 54](https://user-images.githubusercontent.com/33225407/76159474-0aba0680-6121-11ea-92d6-14ac181e8298.png)
It could be related to vcruntime140_1.dll (I tried 2 different versions) but not sure (when I remove it from the path, I guess: vcruntime140_1.dll not found). this happens when I just execute:
securefs (with no parameters)
Happy to run a trace if you tell me how.

**Comment by shuther** [comment]
issue above fixed (reinstall of VC fixed it).
However, securefs still hangs when I create a new file. Trace:
[Trace] [0000000000001804] [2020-03-08 16:03:27.121883100 UTC] [int __cdecl securefs::lite::getattr(const char *,struct fuse_stat *):147]    stat (/Al): mode=040755, uid=0, gid=0, size=0
[Trace] [0000000000001804] [2020-03-08 16:03:27.122066000 UTC] [int __cdecl securefs::lite::create(const char *,unsigned int,struct fuse_file_info *):212]    create path=/Al/b
[Trace] [0000000000001804] [2020-03-08 16:03:27.122189100 UTC] [class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl securefs::lite::FileSystem::translate_path(class securefs::BasicStringRef<char>,bool):158]    Translate path /Al/b into P6N4THHK98DV9ZIZ49Q9D4Y7FVSK4/QJY9BV6C6Q8HYKFYVJI8HRAYZ7PA
[Trace] [0000000000001804] [2020-03-08 16:03:27.144360400 UTC] [__cdecl securefs::WindowsFileStream::WindowsFileStream(class securefs::BasicStringRef<wchar_t>,int,unsigned int):576]    Opening file on a NTFS volume

**Comment by shuther** [comment]
sorry, is there anything I could do to help you debug it?

**Comment by netheril96** [comment]
Probably because file locking is not supported on that volume: https://github.com/netheril96/securefs/blob/aa117ba91122d4375f98e7416eeb244634055c63/sources/lite_fs.cpp#L21

**Comment by netheril96** [comment]
Related to #91

**Comment by netheril96** [comment]
Can you try format 2 on the same condition?

**Comment by shuther** [comment]
so format 2 fixes the issue, but the problem is for me different:
1. Access from an ubuntu box - still through Samba - works
2. It used to work through windows; I tried with default samba configuration (no auxiliary parameters) but still no sucess.
3. smbstatus (v4.10.12)  tell me I am getting locks:
Locked files:
Pid          User(ID)   DenyMode   Access      R/W        Oplock           SharePath   Name   Time
--------------------------------------------------------------------------------------------------
56960        1001       DENY_NONE  0x120089    RDONLY     NONE             /mnt/voluz   other/MSecret/F5ZXUQKNGCJ2HJ6UJZXM5TACPKHC3QVJ72ICUCRWT96A   Sun Mar 22 15:32:57 2020
56960        1001       DENY_NONE  0x120089    RDONLY     NONE             /mnt/voluz   other/MSecret   Sun Mar 22 15:32:17 2020

**Comment by netheril96** [comment]
Try this version, and mount with `--noflock`.

[securefs.zip](https://github.com/netheril96/securefs/files/4365686/securefs.zip)

**Comment by shuther** [comment]
this version is fixing the problem. how safe is this option?

**Comment by netheril96** [comment]
You should run `--noflock` and `--single` and theoretically there shouldn't be any problems. I can't promise that though, since it was never designed to work with nonlockable filesystems in the first place.

**Comment by netheril96** [comment]
Actually according to https://lists.samba.org/archive/samba/2008-January/137877.html, flock should work fine on SMB filesystems. Maybe you should file bugs against your particular SMB implementation?
