### ISSUE TITLE
MAC: user provided "fsname" fuse option is not respected

### ISSUE THREAD

**Issue by mhogomchungu** [netheril96/securefs#96]
Steps to reproduce

1. Unlock securefs volume with "-o fsname=securefs@/path/to/cipherFolder".

2. Observe that the registered device path is NOT "securefs@/path/to/cipherFolder" as expected but it is simply "securefs".

This bug breaks SiriKali and was reported here: https://github.com/mhogomchungu/sirikali/issues/141

**Comment by netheril96** [comment]
`-o` is not intended to be a stable option. It interacts poorly with other set options.

However, the need to set `fsname` is justified. I'll add dedicated options to set `fsname`.
