### ISSUE TITLE
Windows binary reports its version as "0.11.0" instead of "0.11.1"

### ISSUE THREAD

**Issue by mhogomchungu** [netheril96/securefs#99]
The windows executable included in this[1] release reports version "0.11.0" instead of "0.11.1"

[1] https://github.com/netheril96/securefs/releases/tag/0.11.1

```
C:\Users\Ink\bin>securefs version
securefs 0.11.0-2-gdfeebf8
Crypto++ 8.2
WinFsp 1.5
utf8proc 2.5.0

Hardware features available:
SSE2: true
SSE3: true
SSE4.1: true
SSE4.2: true
AES-NI: true
CLMUL: true
SHA: false

C:\Users\Ink\bin>
```

**Comment by netheril96** [comment]
It's actually pointing to the same commit dfeebf8. But indeed it is confusing. I have uploaded a new one.

Thanks for pointing out.
